// SPDX-License-Identifier: Apache-2.0

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	snapshot: (since: number) => __TAURI_INVOKE<Status>("snapshot", { since }),
	/**  Async so the setup (files, threads, AVAudioSession) runs off the main thread. */
	startRecording: () => typedError<string, string>(__TAURI_INVOKE("start_recording")),
	stopRecording: () => __TAURI_INVOKE<void>("stop_recording"),
	markMoment: () => __TAURI_INVOKE<void>("mark_moment"),
};

/* Types */
/**  A finished transcript line. Times are seconds of processed audio. */
export type Line = {
	start: number | null,
	end: number | null,
	/**  1-based diarization speaker. */
	speaker: number | null,
	text: string,
};

export type ModelStatus = {
	id: string,
	/**  Present with the pinned size. */
	ready: boolean,
};

/**  What the session is doing, for the UI and the Live Activity. */
export type Phase = 
/**  Loading the models (first recording only). */
"loading" | "live" | 
/**  The app is in the background: recording only; transcript catches up later. */
"locked" | 
/**  Processing the audio recorded while locked or hot. */
"catchingUp" | 
/**  Thermal state `.serious` or worse: recording only. */
"hot" | 
/**  A phone call or another app took the audio session. */
"interrupted" | 
/**  Stopped; the engine finishes the backlog. */
"finishing" | "done" | 
/**  No engine (not built, models missing or failed): recording only. */
"recordOnly";

export type Snapshot = {
	id: string,
	phase: Phase,
	/**  Capture is running (Stop and Mark apply). */
	recording: boolean,
	elapsedS: number | null,
	/**  Lines from the requested index on. */
	lines: Line[],
	/**  Total number of lines (the next `since`). */
	lineCount: number,
	partial: string,
	marks: (number | null)[],
	stats: Stats,
	error: string | null,
};

export type Stats = {
	/**  Audio recorded, in seconds. */
	recordedS: number | null,
	/**  Audio the engine has processed, in seconds. */
	processedS: number | null,
	/**  Audio waiting for the engine, in seconds. */
	backlogS: number | null,
	/**  Engine compute time / audio time, over the last 10 s of steps. */
	rtf: number | null,
	/**  Audio seconds processed per wall second during the last catch-up. */
	catchUpX: number | null,
	modelLoadS: number | null,
	droppedSamples: number | null,
	/**
	 *  Engine steps (or model loads) that were still running when the app
	 *  went to the background; each one rebuilt the models and streams.
	 */
	gpuOverlaps: number,
	engineResets: number,
	/**  `ProcessInfo.ThermalState`: 0 nominal, 1 fair, 2 serious, 3 critical. */
	thermal: number | null,
	memoryMb: number | null,
	/**  0..1, or `None` when unknown (simulator). */
	battery: number | null,
};

export type Status = {
	/**  The recording in progress, or the last one. */
	session: Snapshot | null,
	models: ModelStatus[],
	/**  This build includes the speech engine. */
	engineBuilt: boolean,
	/**  Where recordings and models live (the app's Documents on iOS). */
	dataDir: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

