// SPDX-License-Identifier: Apache-2.0

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Starts a recording; returns the meeting id. Refused while a call is active
	 *  (`call_active`) until the user has acknowledged M6.
	 */
	recordStart: (start: RecordStart) => typedError<string, string>(__TAURI_INVOKE("record_start", { start })),
	/**  Stops and saves. Safe to call from the Live Activity while locked. */
	recordStop: () => typedError<null, string>(__TAURI_INVOKE("record_stop")),
	recordPause: () => typedError<null, string>(__TAURI_INVOKE("record_pause")),
	/**  Resumes after a user pause or an interruption (restarts the audio engine). */
	recordResume: () => typedError<null, string>(__TAURI_INVOKE("record_resume")),
	/**  Marks the current moment. */
	recordMark: () => typedError<null, string>(__TAURI_INVOKE("record_mark")),
	recordSnapshot: () => typedError<RecordState, string>(__TAURI_INVOKE("record_snapshot")),
	/**
	 *  The consent text for the meeting's `language` (the start language, not the
	 *  UI's), from the user's settings when they wrote their own.
	 */
	recordConsentMessage: (language: MeetingLanguage) => typedError<ConsentMessage, string>(__TAURI_INVOKE("record_consent_message", { language })),
	/**  A phone call is active right now (CXCallObserver). */
	recordCallActive: () => typedError<boolean, string>(__TAURI_INVOKE("record_call_active")),
	/**  The pending "Resume or stop and save?" question after an interruption. */
	recordResumePrompt: () => typedError<ResumePrompt, string>(__TAURI_INVOKE("record_resume_prompt")),
	/**
	 *  Sensitive mode (doc 02, P1) for the running recording: from now on no audio
	 *  is kept (what was written goes when it stops), cloud AI and voice learning
	 *  are refused for the meeting and no final pass runs. One way: part of the
	 *  audio is gone, so a recording cannot leave the mode. Stored meetings use
	 *  `set_meeting_sensitive`.
	 */
	recordSetSensitive: (sensitive: boolean) => typedError<null, string>(__TAURI_INVOKE("record_set_sensitive", { sensitive })),
	/**
	 *  What discarding the last `seconds` of the recording would remove, shown
	 *  before confirming [RT-1].
	 */
	recordDiscardPreview: (seconds: number | null) => typedError<DiscardPreview, string>(__TAURI_INVOKE("record_discard_preview", { seconds })),
	/**
	 *  Discards everything from `from_ms` (meeting time) on [RT-1]: the span the
	 *  user saw in the preview, however long they took to confirm. Returns where
	 *  the cut landed (ms).
	 */
	recordDiscardFrom: (fromMs: number | null) => typedError<number | null, string>(__TAURI_INVOKE("record_discard_from", { fromMs })),
	/**  Where calendar access and the setting stand. Errors: `locked`, `storage`. */
	calendarStatus: () => typedError<CalendarStatus, string>(__TAURI_INVOKE("calendar_status")),
	/**
	 *  Turns the calendar on: shows the system prompt the first time (resolves
	 *  with the answer), then keeps the setting if iOS allows reading events. A
	 *  denied answer leaves it off (`access` says `denied`: the UI points to
	 *  Settings). Errors: `locked`, `storage`.
	 */
	calendarConnect: () => typedError<CalendarStatus, string>(__TAURI_INVOKE("calendar_connect")),
	/**
	 *  Turns the calendar off. iOS keeps the permission (only Settings → Ghira
	 *  takes it back); nothing is read until it is turned on again. Errors:
	 *  `locked`, `storage`.
	 */
	calendarDisconnect: () => typedError<CalendarStatus, string>(__TAURI_INVOKE("calendar_disconnect")),
	/**
	 *  The event in progress (or starting within ten minutes) when the calendar
	 *  is connected; `event` is `null` otherwise. Errors: `locked`, `storage`.
	 */
	calendarCurrentEvent: () => typedError<CurrentEvent, string>(__TAURI_INVOKE("calendar_current_event")),
	appVersion: () => __TAURI_INVOKE<MobileAppVersion>("app_version"),
	lifecycleState: () => typedError<LifecycleState, string>(__TAURI_INVOKE("lifecycle_state")),
	deviceTier: () => typedError<DeviceTier, string>(__TAURI_INVOKE("device_tier")),
	/**  Opens this app's page in the Settings app (microphone denied). */
	openAppSettings: () => __TAURI_INVOKE<void>("open_app_settings"),
	modelsStatus: () => typedError<MobileModelsStatus, string>(__TAURI_INVOKE("models_status")),
	/**
	 *  Downloads what is missing, resuming `.part` files. `wifi_only: false` is the
	 *  user's "download over cellular this time". Progress comes as `MobileEvent::ModelDownload`.
	 *  Refused in strict offline mode (`offline`). A second call while one runs does nothing.
	 */
	modelsDownload: (wifiOnly: boolean) => typedError<null, string>(__TAURI_INVOKE("models_download", { wifiOnly })),
	modelsCancel: () => typedError<null, string>(__TAURI_INVOKE("models_cancel")),
	/**
	 *  Exports everything as an encrypted archive and presents the system share
	 *  sheet (the path never reaches the webview). Resolves once the sheet is
	 *  presented; Swift deletes the archive when the sheet closes.
	 * 
	 *  `password` seals the archive (at least 8 characters, error
	 *  `passwordTooShort`): without it the file is useless, and anyone with the
	 *  file and the password gets every meeting and key.
	 */
	privacyExportAllShare: (password: string) => typedError<null, string>(__TAURI_INVOKE("privacy_export_all_share", { password })),
	/**
	 *  Deletes every meeting, key and setting, including the Keychain items.
	 * 
	 *  `confirm` must be the phrase the user typed in the typed confirmation
	 *  (`DELETE` or `XÓA`, see `privacy_cmd::DELETE_PHRASES`; case and accents
	 *  are ignored); Rust checks it again, so a stray call from the webview
	 *  cannot wipe the phone. Refused while a recording or import runs (`busy`).
	 */
	privacyDeleteAll: (confirm: string) => typedError<null, string>(__TAURI_INVOKE("privacy_delete_all", { confirm })),
	/**
	 *  The chip for each of these meetings (unknown ids are left out). Call it
	 *  with the ids `list_meetings` returned and again on `coreEvent` job changes.
	 */
	meetingChips: (ids: string[]) => typedError<MeetingChipRow[], string>(__TAURI_INVOKE("meeting_chips", { ids })),
	/**
	 *  Renders the meeting (notes and transcript) as Markdown or text into a
	 *  temporary file under the data directory and presents the system share
	 *  sheet for it (the path never reaches the webview). Resolves once the sheet
	 *  is presented; Swift deletes the file when it closes, Rust after an hour or
	 *  at launch. Refused while the app is locked.
	 */
	shareMeetingExport: (meeting: string, format: ShareFormat) => typedError<null, string>(__TAURI_INVOKE("share_meeting_export", { meeting, format })),
	mobileSettings: () => typedError<MobileSettings, string>(__TAURI_INVOKE("mobile_settings")),
	setMobileSettings: (settings: MobileSettings) => typedError<MobileSettings, string>(__TAURI_INVOKE("set_mobile_settings", { settings })),
	/**
	 *  The items waiting, importing or rejected. Items the share extension's user
	 *  already confirmed are imported by the app on its own.
	 */
	inboxList: () => typedError<InboxItem[], string>(__TAURI_INVOKE("inbox_list")),
	/**
	 *  Imports the item with these choices; returns the new meeting id. Errors are
	 *  codes: `notFound`, `busy`, `desktopUnavailable`, and the item's rejection
	 *  reason (`unsupportedType`, `tooLarge`, `unreadable`, ...).
	 */
	inboxConfirm: (id: string, language: MeetingLanguage, target: ProcessingTarget) => typedError<string, string>(__TAURI_INVOKE("inbox_confirm", { id, language, target })),
	/**  Deletes the item and its file. */
	inboxDismiss: (id: string) => typedError<null, string>(__TAURI_INVOKE("inbox_dismiss", { id })),
	onboardingState: () => typedError<OnboardingState, string>(__TAURI_INVOKE("onboarding_state")),
	onboardingCompleteStep: (step: OnboardingStep) => typedError<OnboardingState, string>(__TAURI_INVOKE("onboarding_complete_step", { step })),
	micPermission: () => __TAURI_INVOKE<MicPermission>("mic_permission"),
	/**  Shows the system prompt (only the first time); resolves with the answer. */
	requestMicPermission: () => __TAURI_INVOKE<MicPermission>("request_mic_permission"),
	/**
	 *  The agreement for the next passage (checked before the mic opens). Taking
	 *  it back ends an enrollment in progress and wipes its audio.
	 */
	voiceSetConsent: (given: boolean) => typedError<null, string>(__TAURI_INVOKE("voice_set_consent", { given })),
	/**  Starts capturing the passage. Needs consent and the voice model. */
	voiceEnrollStart: () => typedError<null, string>(__TAURI_INVOKE("voice_enroll_start")),
	/**  Finishes: stores the profile. Errors are the `ghi_app::voice_cmd` codes. */
	voiceEnrollStop: () => typedError<null, string>(__TAURI_INVOKE("voice_enroll_stop")),
	/**  Cancels and wipes the buffered audio. */
	voiceEnrollCancel: () => typedError<null, string>(__TAURI_INVOKE("voice_enroll_cancel")),
	voiceDeleteMe: () => typedError<null, string>(__TAURI_INVOKE("voice_delete_me")),
	/**  Library rows, newest first. */
	listMeetings: (limit: number, offset: number) => typedError<MeetingRow[], string>(__TAURI_INVOKE("list_meetings", { limit, offset })),
	setMeetingTitle: (meeting: string, title: string) => typedError<null, string>(__TAURI_INVOKE("set_meeting_title", { meeting, title })),
	/**
	 *  Deletes a meeting for good (crypto-shred: its key goes, so audio and text
	 *  become unreadable). Not the one being recorded.
	 */
	deleteMeeting: (meeting: string) => typedError<null, string>(__TAURI_INVOKE("delete_meeting", { meeting })),
	/**  Runs a meeting's failed jobs again (the library's "Failed · Retry"). */
	retryMeeting: (meeting: string) => typedError<number, string>(__TAURI_INVOKE("retry_meeting", { meeting })),
	/**
	 *  Meetings recovered after a crash at this launch (D12 "recovered"; the
	 *  notice shows once: the list is cleared when read).
	 */
	takeRecoveredMeetings: () => typedError<RecoveredMeeting[], string>(__TAURI_INVOKE("take_recovered_meetings")),
	/**
	 *  Names of the people the user has named (not Me), most recently met first
	 *  (rename autocomplete).
	 */
	knownSpeakerNames: () => typedError<string[], string>(__TAURI_INVOKE("known_speaker_names")),
	/**
	 *  Sensitive meeting mode (doc 02, P1): no audio kept, no cloud, no voice
	 *  learning. On the meeting being recorded it can only be turned on (part of
	 *  the audio is gone: what was written goes at stop). On a stored meeting
	 *  turning it on deletes its audio now (the UI confirms first); it is refused
	 *  with `noTranscript` (nothing would be kept) or `transcriptPending` (its final
	 *  pass still needs the audio). Turning it off only clears the flag.
	 */
	setMeetingSensitive: (meeting: string, sensitive: boolean) => typedError<null, string>(__TAURI_INVOKE("set_meeting_sensitive", { meeting, sensitive })),
	/**
	 *  The meeting's speakers (merged ones left out), with the middle 3 s of each
	 *  one's longest line as the sample.
	 */
	meetingSpeakers: (meeting: string) => typedError<MeetingSpeaker[], string>(__TAURI_INVOKE("meeting_speakers", { meeting })),
	/**  Names a speaker of a stored meeting (empty name: back to "Speaker N"). */
	renameMeetingSpeaker: (meeting: string, speaker: string, name: string) => typedError<null, string>(__TAURI_INVOKE("rename_meeting_speaker", { meeting, speaker, name })),
	/**
	 *  "This is me": the speaker becomes Me (another Me in the meeting stops
	 *  being Me, and Me's voice samples from this meeting go), and Me's profile
	 *  learns from the speaker's voice. Errors: `liveMeeting`, `notASpeaker`,
	 *  `farSide`, `storage`.
	 */
	setSpeakerMe: (meeting: string, speaker: string) => typedError<null, string>(__TAURI_INVOKE("set_speaker_me", { meeting, speaker })),
	/**
	 *  "Not me": the speaker stops being Me. Errors: `liveMeeting`,
	 *  `notASpeaker`, `notMe`, `farSide` (in a call the mic speaker is always
	 *  Me), `storage`.
	 */
	clearSpeakerMe: (meeting: string, speaker: string) => typedError<null, string>(__TAURI_INVOKE("clear_speaker_me", { meeting, speaker })),
	/**
	 *  Merges `from` into `into` (lines, action items and Me move; `from` is hidden).
	 *  Errors: `liveMeeting`, `notASpeaker`, `sameSpeaker`, `farSide`, `storage`.
	 */
	mergeMeetingSpeakers: (meeting: string, from: string, into: string) => typedError<null, string>(__TAURI_INVOKE("merge_meeting_speakers", { meeting, from, into })),
	/**
	 *  Splits the given lines (or all from `from_segment` on) off a speaker into a
	 *  new one; returns its gid. Errors: `liveMeeting`, `notASpeaker`,
	 *  `nothingToSplit`, `wholeSpeaker`, `storage`.
	 */
	splitMeetingSpeaker: (meeting: string, speaker: string, segmentGids: string[], fromSegment: string | null) => typedError<string, string>(__TAURI_INVOKE("split_meeting_speaker", { meeting, speaker, segmentGids, fromSegment })),
	/**
	 *  Marks a speaker "not a person" or back. Errors: `liveMeeting`, `notASpeaker`,
	 *  `isMe`, `storage`.
	 */
	setSpeakerNotPerson: (meeting: string, speaker: string, notPerson: boolean) => typedError<null, string>(__TAURI_INVOKE("set_speaker_not_person", { meeting, speaker, notPerson })),
	meetingDetail: (meeting: string) => typedError<MeetingDetail, string>(__TAURI_INVOKE("meeting_detail", { meeting })),
	meetingNotes: (meeting: string) => typedError<MeetingNotes, string>(__TAURI_INVOKE("meeting_notes", { meeting })),
	meetingTranscript: (meeting: string) => typedError<MeetingTranscript, string>(__TAURI_INVOKE("meeting_transcript", { meeting })),
	/**  Corrects a transcript line ("Edited"; the final pass keeps it). */
	updateSegmentText: (meeting: string, segment: string, text: string) => typedError<null, string>(__TAURI_INVOKE("update_segment_text", { meeting, segment, text })),
	/**  Moves a transcript line to another speaker of the meeting. */
	setSegmentSpeaker: (meeting: string, segment: string, speaker: string) => typedError<null, string>(__TAURI_INVOKE("set_segment_speaker", { meeting, segment, speaker })),
	/**  Edits a note block (an AI block becomes the user's: `aiEdited`). */
	updateNoteBlock: (meeting: string, block: string, text: string) => typedError<null, string>(__TAURI_INVOKE("update_note_block", { meeting, block, text })),
	/**  Adds one of the user's own notes ("My notes"). */
	addNoteBlock: (meeting: string, text: string) => typedError<NoteBlockView, string>(__TAURI_INVOKE("add_note_block", { meeting, text })),
	deleteNoteBlock: (meeting: string, block: string) => typedError<null, string>(__TAURI_INVOKE("delete_note_block", { meeting, block })),
	addActionItem: (meeting: string, text: string, owner: string | null) => typedError<ActionItemView, string>(__TAURI_INVOKE("add_action_item", { meeting, text, owner })),
	updateActionItem: (meeting: string, item: string, text: string) => typedError<null, string>(__TAURI_INVOKE("update_action_item", { meeting, item, text })),
	setActionDone: (meeting: string, item: string, done: boolean) => typedError<null, string>(__TAURI_INVOKE("set_action_done", { meeting, item, done })),
	/**  Sets (or clears) who owns an action item: one of the meeting's speakers. */
	setActionOwner: (meeting: string, item: string, owner: string | null) => typedError<null, string>(__TAURI_INVOKE("set_action_owner", { meeting, item, owner })),
	deleteActionItem: (meeting: string, item: string) => typedError<null, string>(__TAURI_INVOKE("delete_action_item", { meeting, item })),
	/**  Accent-insensitive search over transcripts and notes (VN-folded). */
	searchMeetings: (request: SearchRequest) => typedError<SearchResults, string>(__TAURI_INVOKE("search_meetings", { request })),
	/**  Plays the whole meeting (the open one; any earlier play token stops working). */
	issueAudioPlay: (meeting: string) => typedError<AudioPlay, string>(__TAURI_INVOKE("issue_audio_play", { meeting })),
	/**
	 *  The waveform of a finished meeting (computed once, then kept sealed in
	 *  the store until the audio goes).
	 */
	waveformPeaks: (meeting: string) => typedError<Waveform, string>(__TAURI_INVOKE("waveform_peaks", { meeting })),
	/**  The meeting as Markdown or plain text, for the clipboard. */
	meetingAsText: (meeting: string, markdown: boolean, content: ExportContent) => typedError<string, string>(__TAURI_INVOKE("meeting_as_text", { meeting, markdown, content })),
	/**  Which providers have a key (never the key). */
	cloudKeys: () => typedError<ProviderKey[], string>(__TAURI_INVOKE("cloud_keys")),
	/**  Stores a provider's API key in the Keychain (from a masked field). */
	setCloudKey: (provider: string, key: string) => typedError<null, string>(__TAURI_INVOKE("set_cloud_key", { provider, key })),
	deleteCloudKey: (provider: string) => typedError<null, string>(__TAURI_INVOKE("delete_cloud_key", { provider })),
	/**  The models with a known price, per provider (the sheet's menus). */
	cloudModels: () => __TAURI_INVOKE<CloudModel[]>("cloud_models"),
	/**  Builds the exact request for the sheet (nothing is sent). */
	cloudPreview: (meeting: string, ask: CloudAsk) => typedError<CloudPreviewResult, string>(__TAURI_INVOKE("cloud_preview", { meeting, ask })),
	/**  Sends the previewed request, exactly. */
	cloudSend: (id: string) => typedError<CloudSendResult, string>(__TAURI_INVOKE("cloud_send", { id })),
	/**  "Never send to cloud" for a meeting. */
	setMeetingCloudLocked: (meeting: string, locked: boolean) => typedError<null, string>(__TAURI_INVOKE("set_meeting_cloud_locked", { meeting, locked })),
	/**  Every cloud request made, newest first (no content is kept). */
	cloudRequestLog: (limit: number) => typedError<CloudLogEntry[], string>(__TAURI_INVOKE("cloud_request_log", { limit })),
	getSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("get_settings")),
	/**  Changes some settings and returns them all. */
	updateSettings: (patch: SettingsPatch) => typedError<AppSettings, string>(__TAURI_INVOKE("update_settings", { patch })),
	vocabulary: () => typedError<Vocabulary, string>(__TAURI_INVOKE("vocabulary")),
	/**  Replaces the user's terms (trimmed, deduplicated, at most 200). */
	setVocabulary: (terms: string[]) => typedError<Vocabulary, string>(__TAURI_INVOKE("set_vocabulary", { terms })),
	/**  Removes a learned name from the vocabulary (it stays removed). */
	ignoreLearnedTerm: (term: string) => typedError<Vocabulary, string>(__TAURI_INVOKE("ignore_learned_term", { term })),
	/**
	 *  Whether the app is locked. The first call after launch locks it when the
	 *  setting is on (nothing is shown before that).
	 */
	lockState: () => typedError<boolean, string>(__TAURI_INVOKE("lock_state")),
	/**  "Lock now" (Settings, and the app menu's "Lock Ghira"). */
	lockNow: () => typedError<boolean, string>(__TAURI_INVOKE("lock_now")),
	/**
	 *  Unlocks after Touch ID or the Mac's password. `reason` is shown in the
	 *  system prompt ("Ghira is trying to <reason>"). False: not confirmed.
	 */
	unlock: (reason: string) => typedError<boolean, string>(__TAURI_INVOKE("unlock", { reason })),
	/**
	 *  Turns the app lock on or off, or changes its idle time. Turning it on or
	 *  off asks first (on: so nobody locks themselves out; off: so nobody at an
	 *  unlocked Mac turns it off); changing the time while on doesn't.
	 */
	setAppLock: (on: boolean, afterMinutes: number, reason: string) => typedError<AppSettings, string>(__TAURI_INVOKE("set_app_lock", { on, afterMinutes, reason })),
	/**  Where the model and Me's profile stand. Errors: `storage`. */
	voiceStatus: () => typedError<VoiceStatus, string>(__TAURI_INVOKE("voice_status")),
	/**
	 *  For the level meter and the timer; poll a few times a second. Errors:
	 *  `notEnrolling`.
	 */
	enrollVoiceLevel: () => typedError<EnrollLevel, string>(__TAURI_INVOKE("enroll_voice_level")),
	/**
	 *  The attendees of the calendar event a recorded meeting was named after
	 *  (rename suggestions list them first). Empty if none. Errors: `storage`.
	 */
	meetingAttendees: (meeting: string) => typedError<string[], string>(__TAURI_INVOKE("meeting_attendees", { meeting })),
	/**
	 *  The attendees of the meeting's calendar event with their addresses (for
	 *  the follow-up email's "To"). Empty if none. Errors: `storage`.
	 */
	meetingContacts: (meeting: string) => typedError<MeetingContact[], string>(__TAURI_INVOKE("meeting_contacts", { meeting })),
};

/** Events */
export const events = {
	coreEvent: makeEvent<CoreEvent>("core-event"),
	lockChanged: makeEvent<LockChanged>("lock-changed"),
	mobileEvent: makeEvent<MobileEvent>("mobile-event"),
};

/* Types */
export type ActionItemView = {
	gid: string,
	text: string,
	ownerSpeakerGid: string | null,
	/**  The due date as spoken ("thứ Sáu"). */
	dueText: string | null,
	done: boolean,
	origin: Origin,
	citations: Citation[],
};

/**
 *  App settings the UI reads (stored in the encrypted store). Every field is
 *  required in the TypeScript type; what the store lacks takes its default.
 */
export type AppSettings = {
	/**  Onboarding finished (or skipped). */
	onboardingDone: boolean,
	/**  Ask to record when a meeting app starts using the mic. */
	detectMeetings: boolean,
	/**  ⌘M / Ctrl+M marks a moment from any app while recording. */
	globalMarkShortcut: boolean,
	/**  ⌘⇧R / Ctrl+Shift+R starts or stops recording from any app. */
	globalRecordShortcut: boolean,
	/**
	 *  Voice profile of the user ("Me"): on while the speaker model is
	 *  installed (the onboarding step is hidden while off).
	 */
	voiceProfilesMe: boolean,
	/**
	 *  Saving other people's voices (consent dialog). Off for the alpha
	 *  ([`THIRD_PARTY_APPROVED`]).
	 */
	voiceProfilesThirdParty: boolean,
	/**  No network at all, model downloads included (doc 02 §L). */
	strictOffline: boolean,
	/**  Language of new meetings: `en`, `vi`, or `auto` (both, code-switching). */
	meetingLanguage: MeetingLanguage,
	/**
	 *  The cloud provider and model the send sheet starts with (empty: none
	 *  chosen yet). Every send is still previewed and confirmed.
	 */
	cloudProvider: string,
	cloudModel: string,
	/**  Hide names and personal data from cloud requests (restored locally). */
	cloudRedact: boolean,
	/**  Days to keep meeting audio (0: until the meeting is deleted). */
	audioRetentionDays: number,
	/**
	 *  The consent message to share at the start of a meeting (empty: the
	 *  built-in text in the app's language).
	 */
	consentMessageEn: string,
	consentMessageVi: string,
	/**  Check for app updates at launch and daily (never under strict offline). */
	updateCheck: boolean,
	/**
	 *  App lock: open locked, lock after `lock_after_minutes` idle and after
	 *  sleep; unlock with Touch ID or the Mac's password (`set_app_lock`).
	 */
	appLock: boolean,
	/**  Idle minutes before the app locks (0: only at launch and after sleep). */
	lockAfterMinutes: number,
	/**
	 *  The live transcript's trade-off (doc 02 §B); applies from the next
	 *  recording. 8 GB Macs always use Fast.
	 */
	liveMode: LiveMode,
	/**  Start Ghira when the user logs in (macOS login item, Windows Run key). */
	openAtLogin: boolean,
	/**  Show the menu-bar / tray icon. */
	showInMenuBar: boolean,
	/**
	 *  The language notes are written in by default (`meeting`: the
	 *  transcript's own).
	 */
	notesLanguage: NotesLanguage,
	/**
	 *  Meeting apps to detect (`zoom`, `teams`, `meet` for browsers, `slack`,
	 *  `zalo`, `webex`, `facetime`); default all. Discord is not on the list:
	 *  it is always detected while `detect_meetings` is on.
	 */
	detectApps: string[],
	/**  Cancel the Mac's speaker output from the mic in call mode. */
	echoCancellation: boolean,
	/**  Capture only the detected meeting app's audio, not the whole system's. */
	appAudioOnly: boolean,
	/**
	 *  Cloud AI is offered ("Cloud, only when you ask"): the per-meeting
	 *  cloud actions appear, each still opt-in and previewed. Off: "On this
	 *  device", and the cloud commands refuse ([`CLOUD_OFF`]).
	 */
	cloudOffered: boolean,
};

/**  An answer to "Ask this meeting". */
export type AskAnswer = {
	/**  False: "Not discussed in this meeting". */
	answered: boolean,
	text: string,
	citations: Citation[],
	/**  The terms looked for (not discussed). */
	searched: string[],
	/**  `local` or the cloud provider. */
	engine: string,
};

/**  The audio bar's source: a play token and how long the audio is. */
export type AudioPlay = {
	token: string,
	durationMs: number | null,
};

/**  What iOS says about calendar access. */
export type CalendarAccess = 
/**  Not on an iPhone (a browser, host tests). */
"unavailable" | "notDetermined" | 
/**  Denied, restricted, or write-only (which cannot read events). */
"denied" | "authorized";

/**
 *  The calendar event in progress (or about to start), as the record screen
 *  shows it. Names only inside a recorded meeting: here a count.
 */
export type CalendarEvent = {
	title: string,
	startMs: number | null,
	endMs: number | null,
	/**  Other attendees. */
	attendees: number,
	/**  `zoom`, `teams`, `meet` or `null`. */
	joinApp: string | null,
};

export type CalendarStatus = {
	access: CalendarAccess,
	/**  The user turned it on and iOS lets the app read events. */
	connected: boolean,
};

/**  A citation resolved against the current transcript. */
export type Citation = {
	t0Ms: number | null,
	t1Ms: number | null,
	/**  The cited words (overlapping segments, shortened). */
	quote: string,
	speakerGid: string | null,
	/**  Made against an older transcript (the text was found by time). */
	stale: boolean,
	/**  Nothing in the transcript at that time ("not found"). */
	missing: boolean,
};

export type CloudAsk = {
	provider: string,
	model: string,
	task: CloudTask,
	/**  Replace names and personal data with placeholders (restored locally). */
	redact: boolean,
	/**  More names to hide besides the speakers'. */
	extraNames: string[],
};

export type CloudLogEntry = {
	meeting: string,
	meetingTitle: string,
	provider: string,
	model: string,
	tokensIn: number | null,
	tokensOut: number | null,
	/**  Unix ms. */
	at: number | null,
};

export type CloudModel = {
	provider: string,
	model: string,
};

/**  The send preview the sheet shows (nothing has left the device). */
export type CloudPreview = {
	/**  Confirm with `cloud_send(id)`. */
	id: string,
	provider: string,
	model: string,
	host: string,
	/**  The request body, byte for byte. */
	payload: string,
	sha256: string,
	tokensEst: number,
	costEstUsd: number | null,
	retentionNote: string,
	/**  Things in the text that still look like personal data. */
	warnings: string[],
	redactions: Redaction[],
	/**
	 *  The request's text as it is on this Mac (names and personal data
	 *  restored), shortened; `None` when it has no user text.
	 */
	excerptBefore: string | null,
	/**  The same text as sent (placeholders for what is hidden). */
	excerptAfter: string | null,
};

export type CloudPreviewResult = {
	kind: "preview",
} & CloudPreview | 
/**  An Ask that nothing matched: answered without any request. */
{
	kind: "answer",
} & AskAnswer;

export type CloudSendResult = 
/**  The notes were rewritten (what the user wrote stays). */
({ kind: "notes" }) & { leftDevice?: never; reason?: never } | {
	kind: "answer",
} & AskAnswer | 
/**
 *  The provider failed: notes are being written on this device instead
 *  (an Ask is answered on this device by the caller).
 */
{ kind: "failed"; reason: string; 
/**  The request may have left the device (it is in the request log). */
leftDevice: boolean };

export type CloudTask = 
/**  Rewrite the notes ("Improve with cloud…"). */
{ kind: "notes"; template: string | null; language: NotesLanguage } | 
/**  Ask this meeting. */
{ kind: "ask"; question: string; language: NotesLanguage };

/**  The copy-the-consent-message text (EN and VI) for the clipboard. */
export type ConsentMessage = {
	en: string,
	vi: string,
	/**
	 *  The one to copy: the meeting's language (both for `auto`), in the user's
	 *  own wording from the settings when they set one.
	 */
	text: string,
};

/**  Every core event, in order (`seq` is gap-free; on a gap, re-read state). */
export type CoreEvent = Envelope;

/**
 *  The answer of `calendar_current_event` (a wrapper: a bare nullable struct
 *  is inlined into the bindings' command line, which the grant check reads).
 */
export type CurrentEvent = {
	event: CalendarEvent | null,
};

export type DeviceTier = {
	/**  `iPhone16,1` style machine identifier (`SIMULATOR_MODEL_IDENTIFIER` on the simulator). */
	modelId: string,
	ramGb: number | null,
	simulator: boolean,
	tier: TierClass,
};

/**  What "discard the last N seconds" would remove, shown before confirming [RT-1]. */
export type DiscardPreview = {
	/**  Where the cut lands (meeting ms). */
	fromMs: number | null,
	/**  Transcript lines that end after the cut. */
	lines: string[],
	/**  Notepad lines typed after the cut. */
	notes: string[],
	marks: number,
};

export type EnrollLevel = {
	/**  Loudness of the latest moment, 0..1. */
	level: number | null,
	/**  Audio buffered so far. */
	seconds: number | null,
	maxSeconds: number | null,
	/**  The mic is closed (the buffer is full or it ran too long): finish. */
	done: boolean,
};

/**
 *  An event with its sequence number (gap-free per bus) and wall time, so a
 *  late subscriber (a reloaded webview) can tell what it missed.
 */
export type Envelope = {
	seq: number | null,
	/**  Unix ms. */
	atMs: number | null,
	event: Event,
};

export type ErrorKind = "permission" | "capture" | "engine" | "modelsMissing" | "storage" | "job";

export type Event = { type: "stateChanged"; meeting: string; state: SessionState } | 
/**
 *  Sent once when a session reaches Recording, right before the
 *  `StateChanged { Recording }` that follows it. `mode` is "call" or
 *  "room" as recorded (a call without system audio is a room).
 */
{ type: "sessionStarted"; meeting: string; mode: string; language: string | null; title: string } | { type: "transcriptPartial"; meeting: string; 
/**  0 = mic, 1 = system. */
track: number; text: string } | { type: "transcriptFinal"; meeting: string; line: LineInfo } | { type: "speakerArrived"; meeting: string; speaker: SpeakerInfo } | 
/**  A provisional speaker became "Speaker N". */
{ type: "speakerConfirmed"; meeting: string; speaker: SpeakerInfo } | { type: "speakerRenamed"; meeting: string; speaker: SpeakerInfo } | { type: "speakersMerged"; meeting: string; from: number; into: number } | 
/**
 *  `lines`: segment gids moved from `from` to the new speaker (each once).
 *  If the store refuses the move, an `Error` event follows and the lines
 *  stay with `from`.
 */
{ type: "speakerSplit"; meeting: string; from: number; speaker: SpeakerInfo; lines: string[] } | { type: "speakerNotAPerson"; meeting: string; id: number } | { type: "markAdded"; meeting: string; tMs: number | null } | 
/**  Everything from `from_ms` on was removed (audio, lines, marks, notes). */
{ type: "discardApplied"; meeting: string; fromMs: number | null } | 
/**
 *  The meeting entered sensitive mode while recording: from now on no
 *  audio is kept (what was written goes at stop), no cloud, no voice
 *  learning. Never turned off again during the same recording.
 */
{ type: "sensitiveChanged"; meeting: string; sensitive: boolean } | 
/**
 *  RMS level of each track over the last ~100 ms (at most 10 per second,
 *  only while audio flows). `None`: the track is not captured or no audio
 *  passed in the window (paused, asleep); digital silence reads -100.
 */
{ type: "levelMeter"; meeting: string; micDbfs: number | null; systemDbfs: number | null } | 
/**
 *  The Mac went to sleep; the timeline stops (the gap is not recorded as
 *  audio) until `Woke` [RT-10].
 */
{ type: "slept"; meeting: string } | { type: "woke"; meeting: string } | 
/**  The system-audio tap was restarted (an output device change). */
{ type: "systemAudioRestarted"; meeting: string } | 
/**
 *  The system track has been digital silence for `silent_s` seconds in a
 *  call: a denied or broken tap (hint: record the room instead).
 */
{ type: "silentSystemTrack"; meeting: string; silentS: number | null } | { type: "diskLow"; meeting: string; freeBytes: number | null } | { type: "diskFull"; meeting: string } | 
/**  A capture device vanished (0 = mic, 1 = system). */
{ type: "trackLost"; meeting: string; track: number } | 
/**
 *  "Only the meeting app's audio" was on but no meeting app was in a call
 *  when recording started: all system audio is recorded instead.
 */
{ type: "appAudioFallback"; meeting: string } | 
/**
 *  After `retry_capture`: the devices are back (also when nothing had
 *  been lost).
 */
{ type: "captureRecovered"; meeting: string } | 
/**  After `retry_capture`: the devices could not be rebuilt. */
{ type: "captureRetryFailed"; meeting: string; message: string } | 
/**
 *  The audio route changed; `bluetooth_hfp`: the input is a Bluetooth
 *  headset, whose mic drops the whole link to call quality.
 */
{ type: "routeChanged"; meeting: string; bluetoothHfp: boolean } | { type: "health"; meeting: string; 
/**  Seconds the live transcript trails the audio. */
asrLagS: number | null; 
/**  Audio skipped by ASR so far (seconds; the final pass fills it). */
asrSkippedS: number | null; aec: boolean } | { type: "jobProgress"; meeting: string | null; job: number | null; kind: string; stage: Stage | null; 
/**  0..1 within the job. */
progress: number | null } | { type: "notesReady"; meeting: string; 
/**  1 = from the live transcript, 2 = after the final pass. */
version: number } | { type: "error"; meeting: string | null; kind: ErrorKind; message: string };

/**  What goes into the file; headings in the app's language. */
export type ExportContent = {
	notes: boolean,
	transcript: boolean,
	/**  Headings in Vietnamese (else English). */
	vietnamese: boolean,
};

export type InboxItem = {
	/**  The inbox folder's uuid. */
	id: string,
	/**  The shared file's name (shown as the title). */
	name: string,
	sizeBytes: number | null,
	language: MeetingLanguage,
	target: ProcessingTarget,
	state: InboxState,
	/**  Set when `state` is `Rejected`: a code the UI turns into words. */
	reason: string | null,
};

export type InboxState = 
/**  Waiting for the user to confirm language and target (the extension closed early). */
"pending" | "importing" | 
/**  Could not be imported (unsupported type such as CAF, too large, unreadable). */
"rejected";

/**  Why the audio session was interrupted. */
export type InterruptionKind = 
/**  A phone call (the M6 notice). */
"call" | "other";

export type LifecycleState = {
	scene: Scene,
	/**  Dynamic Type multiplier, capped at 2.0. */
	textScale: number | null,
	/**  `ProcessInfo.thermalState` raw value, 0 to 3. */
	thermal: number,
};

/**  A final transcript line. */
export type LineInfo = {
	/**  Store segment gid (empty until persisted). */
	gid: string,
	speaker: number | null,
	t0Ms: number | null,
	t1Ms: number | null,
	text: string,
	/**  Two speakers talked over each other. */
	overlap: boolean,
	words: WordInfo[],
};

export type LiveMode = 
/**  Chosen by the hardware tier. */
"auto" | 
/**  Lighter on the Mac; captions come a little later (1.1 s chunks). */
"fast" | 
/**  Captions sooner, more processing while recording (0.56 s chunks). */
"accurate";

/**  The lock changed (every window follows it). */
export type LockChanged = {
	locked: boolean,
};

export type MarkView = {
	tMs: number | null,
	/**  `mark`, `decision`, `action`, `question`. */
	tag: string,
};

export type MeProfile = {
	/**  When they agreed (unix ms). */
	atMs: number | null,
	/**  Voice samples kept (windows of their speech). */
	samples: number,
};

/**
 *  The status chip on a meeting row (M3). v1 produces only the first five;
 *  the last three are phase 15 and are never sent before pairing exists.
 */
export type MeetingChip = { kind: "recorded" } | { kind: "processingOnPhone"; percent: number } | { kind: "processedOnPhone" } | { kind: "waitingForModels" } | { kind: "failed" } | { kind: "synced" } | { kind: "waitingForWifi" } | { kind: "finalOnDesktop"; percent: number };

export type MeetingChipRow = {
	gid: string,
	chip: MeetingChip,
};

/**  An attendee of the calendar event a meeting was recorded in. */
export type MeetingContact = {
	name: string,
	/**  `None` when the invite had no address. */
	email: string | null,
};

export type MeetingDetail = {
	gid: string,
	title: string,
	/**  Unix ms. */
	startedAt: number | null,
	durationMs: number | null,
	/**  `live`, `import`, … */
	source: string,
	/**  `call` or `room`. */
	mode: string,
	/**  The transcript's language (`en`, `vi`, `mixed`), if known. */
	language: string | null,
	/**  Notes template id (`None`: the default, `general`). */
	template: string | null,
	status: string,
	cloudLocked: boolean,
	sensitive: boolean,
	cloudUsed: boolean,
	consentConfirmed: boolean,
	transcriptVersion: number | null,
	/**  Some audio is kept (retention may have removed it). */
	audioAvailable: boolean,
	speakers: MeetingSpeaker[],
	job: MeetingJob | null,
	/**
	 *  The model that wrote the current notes (`None`: no notes, or written
	 *  before this was recorded).
	 */
	notesModel: string | null,
	/**
	 *  Where an imported file came from: `zoom`, `teams`, `meet`, `plaud`,
	 *  `voice_memos`.
	 */
	sourceApp: string | null,
};

/**  What the library shows about a meeting's processing. */
export type MeetingJob = {
	/**  `notes_live`, `final_pass`, `notes_final`. */
	kind: string,
	/**  0..1. */
	progress: number | null,
	/**  Queued until its models are installed (record now, process later). */
	waitingForModels: boolean,
};

export type MeetingLanguage = "en" | "vi" | "auto";

export type MeetingNotes = {
	blocks: NoteBlockView[],
	actionItems: ActionItemView[],
	/**  The meeting template's own sections (for `section:<id>` blocks). */
	sections: TemplateSection[],
};

export type MeetingRow = {
	gid: string,
	title: string,
	/**  Unix ms. */
	startedAt: number | null,
	durationMs: number | null,
	/**  `live`, `import`, … */
	source: string,
	/**  `call` or `room`. */
	mode: string,
	/**  `recording`, `done`, `processing`, `ready`, … */
	status: string,
	transcriptVersion: number | null,
	cloudUsed: boolean,
	consentConfirmed: boolean,
	/**  Sensitive mode: no audio kept, no cloud, no voice learning. */
	sensitive: boolean,
	/**  Notes template id (`None`: the default). */
	template: string | null,
	/**  Named speakers, for the people column and filter. */
	people: PersonChip[],
	/**  The active job, if any. */
	job: MeetingJob | null,
	/**  The folder's gid (`list_folders` has the names); `None`: no folder. */
	folder: string | null,
	tags: TagChip[],
	/**
	 *  Where an imported file came from: `zoom`, `teams`, `meet`, `plaud`,
	 *  `voice_memos`.
	 */
	sourceApp: string | null,
	/**
	 *  The first TL;DR line of the notes (the row's second line); `None`
	 *  while the meeting has no notes.
	 */
	summary: string | null,
	/**  Speakers still without a name (not Me, not "not a person"). */
	unnamedVoices: number,
};

export type MeetingSpeaker = {
	gid: string,
	/**  The user's name for them, if any. */
	name: string | null,
	/**  1-based number shown as "Speaker N" while unnamed. */
	number: number,
	/**  Palette slot 1..8 (0: Others). */
	colorSlot: number,
	isMe: boolean,
	notPerson: boolean,
	lines: number,
	/**  A span of their speech for the sample (meeting ms, at most 3 s). */
	sampleT0Ms: number | null,
	sampleT1Ms: number | null,
	/**
	 *  "Sounds like ..." from the final pass's voice matching, until the user
	 *  names the speaker, accepts or dismisses it.
	 */
	suggestion: VoiceSuggestion | null,
};

export type MeetingTranscript = {
	version: number | null,
	segments: SegmentView[],
	marks: MarkView[],
	/**  Topic headers (from the notes), in time order. */
	topics: TopicView[],
};

export type MicPermission = "notDetermined" | "granted" | "denied";

export type MobileAppVersion = {
	app: string,
	core: string,
};

export type MobileEvent = 
/**  The recording phase changed. */
{ type: "phase"; phase: RecordPhase } | 
/**  Audio recorded while locked or hot that the transcript has not caught up with. */
{ type: "backlog"; backlogS: number | null; catchUpX: number | null } | 
/**  The microphone sounds muffled (a pocket or bag): warn, clear when it passes. */
{ type: "pocket"; muffled: boolean } | 
/**
 *  The audio session was interrupted (began) or the interruption ended.
 *  Recording never resumes by itself: the UI asks (`record_resume_prompt`).
 */
{ type: "interruption"; began: boolean; kind: InterruptionKind } | 
/**  `ProcessInfo.thermalState` raw value, 0 nominal to 3 critical. */
{ type: "thermal"; level: number } | 
/**  Dynamic Type as a multiplier, capped at 2.0 (the CSS variable `--ghi-text-scale`). */
{ type: "textScale"; scale: number | null } | 
/**  The share extension added files to the App Group inbox. */
{ type: "inboxChanged" } | 
/**  The audio route changed (`AVAudioSession.RouteChangeReason` raw value). */
{ type: "route"; reason: number } | 
/**  The system warned about memory. */
{ type: "memoryWarning" } | 
/**  A model download moved on. */
{ type: "modelDownload"; item: MobileModelItem } | 
/**  A phone call started or ended (the M6 notice blocks Record while active). */
{ type: "callActive"; active: boolean };

export type MobileModelItem = {
	id: string,
	role: MobileModelRole,
	sizeBytes: number | null,
	receivedBytes: number | null,
	state: MobileModelState,
};

export type MobileModelRole = "asr" | "diarization" | "voice";

export type MobileModelState = "missing" | "downloading" | "ready" | 
/**  Waiting for Wi-Fi (the default is Wi-Fi only). */
"waitingForWifi" | "failed";

export type MobileModelsStatus = {
	items: MobileModelItem[],
	/**  Total download size of what is missing. */
	missingBytes: number | null,
	wifiOnly: boolean,
};

export type MobileSettings = {
	/**
	 *  What new recordings and imports use (Settings → Processing). `Desktop`
	 *  is rejected until phase 15.
	 */
	defaultTarget: ProcessingTarget,
	/**  Download models over Wi-Fi only (default true). */
	modelsWifiOnly: boolean,
};

export type NoteBlockView = {
	gid: string,
	/**
	 *  `tldr`, `decision`, `question`, `quote`, `topic`, `section:<id>`,
	 *  `enhanced:<user block gid>` (the AI's expansion of a user note; an
	 *  empty text means "not found"), or the user's `note` / `decision` /
	 *  `action` / `question`.
	 */
	kind: string,
	origin: Origin,
	text: string,
	pinned: boolean,
	citations: Citation[],
};

/**  The language notes are written in. */
export type NotesLanguage = 
/**  The meeting's own (dominant) language. */
"meeting" | "en" | "vi";

export type OnboardingState = {
	completed: OnboardingStep[],
	/**  Pairing exists (phase 15). False in v1. */
	syncAvailable: boolean,
};

export type OnboardingStep = "languages" | "micPriming" | "voice" | "consent" | 
/**  Phase 15; hidden while `sync_available` is false. */
"pair" | "processing" | "models" | "done";

export type Origin = "user" | "ai" | 
/**  AI-written, then changed by the user (kept by a regenerate). */
"aiEdited";

/**  A named speaker as a chip: color + initial (never color alone). */
export type PersonChip = {
	name: string,
	/**  Palette slot 1..8 (0: Others). */
	colorSlot: number,
	/**  The user ("Me"): shown as "Me" in the app's language, whatever `name`. */
	isMe: boolean,
};

/**  Where a recording is processed after it stops. */
export type ProcessingTarget = 
/**  The final pass runs on this phone (needs the speech models and a capable device). */
"phone" | 
/**  Phase 15: a paired desktop. Listed but disabled until pairing exists. */
"desktop" | 
/**
 *  Notes through the user's own cloud key, transcript text only, per
 *  meeting and after a preview. The transcript itself is still made on the phone.
 */
"cloud";

export type ProviderKey = {
	provider: string,
	stored: boolean,
};

/**
 *  v1 records in a room (the phone's microphone). Calls are not captured; M6
 *  tells the user to use speakerphone and Room mode.
 */
export type RecordMode = "room";

export type RecordOnlyReason = 
/**  The device is below the live tier (iPhone 15 and RAM >= 6 GB). */
"deviceTier" | "modelsMissing" | "thermal" | "engineFailed";

/**  What the session is doing, for the UI and the Live Activity. */
export type RecordPhase = "idle" | 
/**  Loading the models (first recording, or after a reload). */
"loading" | "live" | 
/**  The app is in the background: recording only; the transcript catches up later. */
"locked" | "catchingUp" | 
/**  Thermal state serious or worse: recording only. */
"hot" | 
/**  A phone call or another app took the audio session; waiting for the user to resume. */
"interrupted" | 
/**  Paused by the user. */
"paused" | 
/**  Stopped; the engine finishes the backlog. */
"finishing" | "done" | 
/**  No live engine (device below tier, models missing or failed): recording only. */
"recordOnly";

export type RecordStart = {
	mode: RecordMode,
	language: MeetingLanguage,
	/**  A title, or `None` for the generated one. */
	title: string | null,
	target: ProcessingTarget,
	/**  The user agreed that everyone being recorded knows (M2 reminder). */
	consentAcknowledged: boolean,
	/**
	 *  The user saw the M6 notice (use speakerphone and Room mode) while a
	 *  phone call is active. Only this lifts the call block; the consent flag
	 *  above never does.
	 */
	callAcknowledged: boolean,
	/**
	 *  Sensitive mode from the start: no audio is kept (transcript only), no
	 *  cloud, no voice learning. Needs the live transcript (`sensitiveNeedsTranscript`
	 *  otherwise).
	 */
	sensitive: boolean,
};

/**
 *  The recording as it stands now, for a reloaded webview: apply `coreEvent`s
 *  with a greater `seq` after `session`. Idle (nothing recorded): `phase` is
 *  `idle` and `session` is `None`.
 * 
 *  Two states exist and answer different questions. `phase` (and
 *  `MobileEvent::Phase`) is the *iOS lifecycle* state of the recording: locked,
 *  catching up, hot, interrupted, paused. `session.state` (from `coreEvent`) is
 *  the *core* session state shared with the desktop (recording / paused /
 *  stopping). The UI shows `phase`; it never infers one from the other.
 */
export type RecordState = {
	phase: RecordPhase,
	/**
	 *  Capture is running (audio is being recorded), whatever the live
	 *  transcript is doing: `phase` may say `loading` or `locked` mid-meeting
	 *  while this stays true, and the elapsed time keeps counting. False when
	 *  paused, interrupted, stopped or idle.
	 */
	recording: boolean,
	/**  Recorded seconds (not wall time: a pause does not count). */
	elapsedS: number | null,
	marks: number,
	/**  Latest input level, dBFS (<= 0). */
	levelDb: number | null,
	backlogS: number | null,
	catchUpX: number | null,
	pocket: boolean,
	/**  The live transcript is being made on this phone. */
	live: boolean,
	/**  Why there is no live transcript, when there is none. */
	recordOnlyReason: RecordOnlyReason | null,
	session: SessionSnapshot | null,
};

/**  A meeting closed by crash recovery at this launch. */
export type RecoveredMeeting = {
	gid: string,
	title: string,
	/**  What was saved (ms). */
	durationMs: number | null,
};

export type Redaction = {
	kind: string,
	count: number,
};

/**
 *  What to ask after an interruption ended. `pending` is false when there is
 *  nothing to ask (the other fields are then empty).
 */
export type ResumePrompt = {
	pending: boolean,
	meeting: string,
	/**  Seconds recorded before the interruption. */
	recordedS: number | null,
	/**  The interruption was a phone call. */
	call: boolean,
};

/**
 *  The app's scene. `lifecycle_state` is a stub for the scene until 16-E
 *  reports it from Swift (`willResignActive` / `didEnterBackground`); it always
 *  answers `active` now. Live phase changes arrive as `MobileEvent::Phase`.
 */
export type Scene = "active" | 
/**  Resigned active (app switcher, a system sheet, locking). */
"inactive" | "background";

export type SearchHitView = {
	/**  `segment` or `note`. */
	kind: string,
	meeting: string,
	meetingTitle: string,
	meetingStartedAt: number | null,
	/**  Segment or note block gid. */
	item: string,
	speakerGid: string | null,
	t0Ms: number | null,
	t1Ms: number | null,
	snippet: string,
	/**  `[start, end)` in UTF-16 code units of `snippet` (JS string indexes). */
	highlights: ([number, number])[],
	/**  The accented query matched exactly (ranked first). */
	exact: boolean,
};

export type SearchRequest = {
	text: string,
	/**  `live` or `file`. */
	source: string | null,
	template: string | null,
	/**  Meeting start range, unix ms, inclusive. */
	fromMs: number | null,
	toMs: number | null,
	/**  Only this meeting ("Find" inside a meeting uses the transcript instead). */
	meeting: string | null,
	/**  Only meetings in this folder (gid); `""` means meetings in no folder. */
	folder?: string | null,
	/**  Only meetings with any of these tags (gids; none: no restriction). */
	tags?: string[] | null,
	limit: number,
	offset: number,
};

export type SearchResults = {
	hits: SearchHitView[],
	/**  More matches exist than were considered. */
	truncated: boolean,
};

export type SegmentView = {
	gid: string,
	speakerGid: string | null,
	t0Ms: number | null,
	t1Ms: number | null,
	text: string,
	language: string | null,
	confidence: number | null,
	/**  The user changed the text ("Edited"). */
	edited: boolean,
	/**  Another speaker talked over this line: some words may be wrong. */
	overlap: boolean,
	/**
	 *  One per space-separated word of `text`, in order (empty when the
	 *  counts don't match, e.g. after an edit).
	 */
	words: WordTiming[],
};

/**
 *  Everything a reloaded webview needs to redraw a running session. `seq` is
 *  the bus sequence number read before the rest was gathered: events with a
 *  greater `seq` may repeat what is here (lines are told apart by `gid`).
 */
export type SessionSnapshot = {
	seq: number | null,
	meeting: string,
	state: SessionState,
	nowMs: number | null,
	/**  A live transcript is being made (false: models missing). */
	transcribing: boolean,
	/**  "call" or "room" (after the call-without-system-audio fallback). */
	mode: string,
	language: string | null,
	title: string,
	/**  Everyone's consent to recording was confirmed (the live toggle). */
	consentConfirmed: boolean,
	/**  Sensitive mode: no audio is kept for this meeting. */
	sensitive: boolean,
	/**  Speakers still in play (merged ones are gone). */
	speakers: SpeakerInfo[],
	/**  Final lines stored so far, in time order. */
	lines: LineInfo[],
	/**  Marks (ms), in time order. */
	marks: (number | null)[],
};

/**  SessionManager states (brief §7, the Record control). */
export type SessionState = "idle" | "starting" | "recording" | "paused" | "stopping" | "processing" | "ready" | "failed";

/**  A change to some settings; fields left out keep their value. */
export type SettingsPatch = {
	onboardingDone?: boolean | null,
	detectMeetings?: boolean | null,
	globalMarkShortcut?: boolean | null,
	globalRecordShortcut?: boolean | null,
	strictOffline?: boolean | null,
	meetingLanguage?: MeetingLanguage | null,
	cloudProvider?: string | null,
	cloudModel?: string | null,
	cloudRedact?: boolean | null,
	audioRetentionDays?: number | null,
	consentMessageEn?: string | null,
	consentMessageVi?: string | null,
	updateCheck?: boolean | null,
	liveMode?: LiveMode | null,
	openAtLogin?: boolean | null,
	showInMenuBar?: boolean | null,
	notesLanguage?: NotesLanguage | null,
	detectApps?: string[] | null,
	echoCancellation?: boolean | null,
	appAudioOnly?: boolean | null,
	cloudOffered?: boolean | null,
};

/**  The file kinds the share sheet offers for a meeting. */
export type ShareFormat = "md" | "txt";

export type SpeakerInfo = {
	/**  Session speaker id (stable for the meeting). */
	id: number,
	/**  What the UI shows: a name, "Me", "Speaker N" or "Identifying…". */
	label: string,
	/**  1..=8, or 0 for the shared Others lane. */
	colorSlot: number,
	isMe: boolean,
	provisional: boolean,
	notPerson: boolean,
	others: boolean,
};

/**  Final-pass stages, in order (shown as progress in the UI). */
export type Stage = "decoding" | "refiningSpeakers" | "matchingVoices" | "improvingTranscript" | "writingNotes";

/**  A tag on a meeting row. */
export type TagChip = {
	gid: string,
	name: string,
};

export type TemplateSection = {
	id: string,
	titleEn: string,
	titleVi: string,
};

/**  What the device can do (`tier.rs`). */
export type TierClass = 
/**  Live transcript and the on-phone final pass. */
"live" | 
/**  Records only; no on-phone transcript. The `Phone` target is disabled. */
"recordOnly";

export type TopicView = {
	title: string,
	tMs: number | null,
};

export type Vocabulary = {
	/**  The user's own terms (names, products, jargon), as written. */
	terms: string[],
	/**  Names learned from the speakers the user named (removable). */
	learned: string[],
	maxTerms: number,
};

export type VoiceStatus = {
	/**  The speaker model is installed. */
	modelReady: boolean,
	meProfile: MeProfile | null,
	enrolling: boolean,
};

export type VoiceSuggestion = {
	personGid: string,
	/**  The person's name (empty for Me: show "Me"). */
	name: string,
	isMe: boolean,
	/**  Cosine similarity, 0.5..1. */
	score: number | null,
};

/**  The audio bar's waveform. */
export type Waveform = {
	perSecond: number,
	/**  Loudness 0..255 per bucket, from the start of the meeting. */
	peaks: number[],
};

export type WordInfo = {
	text: string,
	t0Ms: number | null,
	t1Ms: number | null,
	lowConfidence: boolean,
};

export type WordTiming = {
	t0Ms: number | null,
	t1Ms: number | null,
	/**  0..1, if the engine gave one. */
	confidence: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

