# cargo-about: generates THIRD_PARTY_NOTICES.html for Settings → About → Licenses.
# Run: cargo about generate about.hbs -o THIRD_PARTY_NOTICES.html
accepted = [
  "Apache-2.0",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "MPL-2.0",
  "OFL-1.1",
  "Unicode-3.0",
  "CC0-1.0",
  "CDLA-Permissive-2.0",
  "Apache-2.0 WITH LLVM-exception",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true
workarounds = ["ring"]
