[workspace]
resolver = "3"
members = ["crates/*", "apps/desktop/src-tauri"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["The Ghi Authors"]
publish = false

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "warn"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
