// SPDX-License-Identifier: Apache-2.0
fn main() {
    // NeMo-Speech.cpp (`--features nemo`): the app bundle ships its dylibs in
    // Contents/Frameworks (tools/release/stage-bundle.sh). Debug builds also
    // find them where tools/scripts/build-nemo.sh installed them; release
    // builds don't carry that build path.
    println!("cargo:rerun-if-env-changed=DEP_NEMO_SPEECH_ASR_C_LIBDIR");
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos") {
        println!("cargo:rustc-link-arg=-Wl,-rpath,@executable_path/../Frameworks");
    }
    if let Ok(dir) = std::env::var("DEP_NEMO_SPEECH_ASR_C_LIBDIR")
        && std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows")
        && std::env::var("PROFILE").as_deref() != Ok("release")
    {
        println!("cargo:rustc-link-arg=-Wl,-rpath,{dir}");
    }
    // Declaring app commands makes each one need an explicit capability grant
    // (`allow-<command>` in capabilities/*.json) instead of being open to every window.
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "app_version",
            "start_recording",
            "stop_recording",
            "pause_recording",
            "resume_recording",
            "mark_moment",
            "discard_last",
            "discard_from",
            "rename_speaker",
            "merge_speakers",
            "split_speaker",
            "speaker_not_a_person",
            "quit_app",
            "list_meetings",
            "set_meeting_title",
            "note_lines",
            "add_note_line",
            "update_note_line",
            "delete_note_line",
            "discard_preview",
            "get_settings",
            "update_settings",
            "mic_permission",
            "request_mic_permission",
            "reply_meeting_detected",
            "issue_audio_sample",
            "show_main",
            "set_consent_confirmed",
            "session_snapshot",
            "models_status",
            "download_models",
            "cancel_model_download",
            "delete_meeting",
            "retry_meeting",
            "take_recovered_meetings",
            "known_speaker_names",
            "hide_popover",
            "set_mini_compact",
            "close_mini",
            "open_mini_recorder",
            "close_detect",
            "show_notification",
            "request_quit_app",
            "meeting_speakers",
            "rename_meeting_speaker",
            "has_recovery_key",
            "create_recovery_key",
            "confirm_recovery_key",
            "cancel_recovery_key",
            "open_privacy_settings",
            "test_capture",
            "install_update",
            "check_for_updates",
            "update_status",
            "acknowledge_crash",
            "reveal_diagnostics",
            "diagnostics_status",
            "draft_followup_email",
            "take_dropped_files",
            "delete_all_data",
            "export_everything",
            "ignore_learned_term",
            "set_vocabulary",
            "vocabulary",
            "ask_meeting",
            "cloud_request_log",
            "set_meeting_cloud_locked",
            "cloud_send",
            "cloud_preview",
            "cloud_models",
            "delete_cloud_key",
            "set_cloud_key",
            "cloud_keys",
            "cancel_import",
            "start_import",
            "unstage_files",
            "staged_files",
            "pick_import_files",
            "reveal_last_export",
            "meeting_as_text",
            "export_obsidian",
            "export_meetings",
            "export_meeting",
            "waveform_peaks",
            "issue_audio_play",
            "search_meetings",
            "regenerate_notes",
            "list_templates",
            "delete_action_item",
            "set_action_owner",
            "set_action_done",
            "update_action_item",
            "add_action_item",
            "delete_note_block",
            "add_note_block",
            "update_note_block",
            "set_segment_speaker",
            "update_segment_text",
            "meeting_transcript",
            "meeting_notes",
            "meeting_detail",
        ]),
    ))
    .expect("failed to run tauri-build");
}
