// SPDX-License-Identifier: Apache-2.0

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appVersion: () => __TAURI_INVOKE<AppVersion>("app_version"),
	startRecording: (mode: RecordMode, language: string | null, title: string) => typedError<string, string>(__TAURI_INVOKE("start_recording", { mode, language, title })),
	stopRecording: () => typedError<Stopped, string>(__TAURI_INVOKE("stop_recording")),
	pauseRecording: () => typedError<null, string>(__TAURI_INVOKE("pause_recording")),
	resumeRecording: () => typedError<null, string>(__TAURI_INVOKE("resume_recording")),
	/**  Marks this moment; returns its meeting time (ms). */
	markMoment: () => typedError<number | null, string>(__TAURI_INVOKE("mark_moment")),
	/**  Discards the last `seconds` [RT-1]; returns where the cut landed (ms). */
	discardLast: (seconds: number | null) => typedError<number | null, string>(__TAURI_INVOKE("discard_last", { seconds })),
	/**
	 *  Discards everything from `from_ms` (meeting time) on [RT-1]: the span the
	 *  user saw in the preview, however long they took to confirm.
	 */
	discardFrom: (fromMs: number | null) => typedError<number | null, string>(__TAURI_INVOKE("discard_from", { fromMs })),
	renameSpeaker: (id: number, name: string) => typedError<null, string>(__TAURI_INVOKE("rename_speaker", { id, name })),
	mergeSpeakers: (from: number, into: number) => typedError<null, string>(__TAURI_INVOKE("merge_speakers", { from, into })),
	/**  Moves the given lines (segment gids) to a new speaker; returns its id. */
	splitSpeaker: (from: number, lines: string[]) => typedError<number | null, string>(__TAURI_INVOKE("split_speaker", { from, lines })),
	speakerNotAPerson: (id: number) => typedError<null, string>(__TAURI_INVOKE("speaker_not_a_person", { id })),
	/**
	 *  Quits; `stop`: stop the recording first (it is saved and processed at the
	 *  next launch). Without `stop`, a running recording keeps the app open.
	 */
	quitApp: (stop: boolean) => typedError<null, string>(__TAURI_INVOKE("quit_app", { stop })),
	/**  Quit from the popover (the menu bar has no app menu on Windows). */
	requestQuitApp: () => __TAURI_INVOKE<void>("request_quit_app"),
	/**  Library rows, newest first. */
	listMeetings: (limit: number, offset: number) => typedError<MeetingRow[], string>(__TAURI_INVOKE("list_meetings", { limit, offset })),
	setMeetingTitle: (meeting: string, title: string) => typedError<null, string>(__TAURI_INVOKE("set_meeting_title", { meeting, title })),
	/**  The user's own lines of a meeting, in time order. */
	noteLines: (meeting: string) => typedError<NoteLine[], string>(__TAURI_INVOKE("note_lines", { meeting })),
	/**
	 *  Adds a notepad line at meeting time `tMs` (invisible anchor: the line links
	 *  to that moment). A tagged kind also leaves a mark there.
	 */
	addNoteLine: (meeting: string, text: string, tMs: number | null, kind: NoteKind) => typedError<NoteLine, string>(__TAURI_INVOKE("add_note_line", { meeting, text, tMs, kind })),
	updateNoteLine: (meeting: string, line: string, text: string) => typedError<null, string>(__TAURI_INVOKE("update_note_line", { meeting, line, text })),
	deleteNoteLine: (meeting: string, line: string) => typedError<null, string>(__TAURI_INVOKE("delete_note_line", { meeting, line })),
	discardPreview: (seconds: number | null) => typedError<DiscardPreview, string>(__TAURI_INVOKE("discard_preview", { seconds })),
	/**  The "Consent confirmed" toggle of a meeting [RT-14]. */
	setConsentConfirmed: (meeting: string, confirmed: boolean) => typedError<null, string>(__TAURI_INVOKE("set_consent_confirmed", { meeting, confirmed })),
	/**
	 *  The recording in progress as it stands now (a reloaded webview, a second
	 *  window): apply events with a greater `seq` after it. `None` when idle.
	 */
	sessionSnapshot: () => typedError<{
	seq: number | null,
	meeting: string,
	state: SessionState,
	nowMs: number | null,
	/**  A live transcript is being made (false: models missing). */
	transcribing: boolean,
	/**  "call" or "room" (after the call-without-system-audio fallback). */
	mode: string,
	language: string | null,
	title: string,
	/**  Everyone's consent to recording was confirmed (the live toggle). */
	consentConfirmed: boolean,
	/**  Speakers still in play (merged ones are gone). */
	speakers: SpeakerInfo[],
	/**  Final lines stored so far, in time order. */
	lines: LineInfo[],
	/**  Marks (ms), in time order. */
	marks: (number | null)[],
} | null, string>(__TAURI_INVOKE("session_snapshot")),
	/**
	 *  Deletes a meeting for good (crypto-shred: its key goes, so audio and text
	 *  become unreadable). Not the one being recorded.
	 */
	deleteMeeting: (meeting: string) => typedError<null, string>(__TAURI_INVOKE("delete_meeting", { meeting })),
	/**  Runs a meeting's failed jobs again (the library's "Failed · Retry"). */
	retryMeeting: (meeting: string) => typedError<number, string>(__TAURI_INVOKE("retry_meeting", { meeting })),
	/**
	 *  Meetings recovered after a crash at this launch (D12 "recovered"; the
	 *  notice shows once: the list is cleared when read).
	 */
	takeRecoveredMeetings: () => typedError<RecoveredMeeting[], string>(__TAURI_INVOKE("take_recovered_meetings")),
	/**
	 *  Names given to speakers in recent meetings, most recent first (rename
	 *  autocomplete; the People list arrives in phase 14).
	 */
	knownSpeakerNames: () => typedError<string[], string>(__TAURI_INVOKE("known_speaker_names")),
	/**
	 *  The meeting's speakers (merged ones left out), with the middle 3 s of each
	 *  one's longest line as the sample.
	 */
	meetingSpeakers: (meeting: string) => typedError<MeetingSpeaker[], string>(__TAURI_INVOKE("meeting_speakers", { meeting })),
	/**  Names a speaker of a stored meeting (empty name: back to "Speaker N"). */
	renameMeetingSpeaker: (meeting: string, speaker: string, name: string) => typedError<null, string>(__TAURI_INVOKE("rename_meeting_speaker", { meeting, speaker, name })),
	/**  Whether a recovery key is set up. */
	hasRecoveryKey: () => typedError<boolean, string>(__TAURI_INVOKE("has_recovery_key")),
	/**  A new phrase to write down (not stored until confirmed). */
	createRecoveryKey: () => __TAURI_INVOKE<string[]>("create_recovery_key"),
	/**  Stores the pending phrase if `words` (the whole phrase, typed back) match. */
	confirmRecoveryKey: (words: string[]) => typedError<boolean, string>(__TAURI_INVOKE("confirm_recovery_key", { words })),
	/**  Forgets a phrase that was shown but not confirmed. */
	cancelRecoveryKey: () => __TAURI_INVOKE<void>("cancel_recovery_key"),
	/**  Opens System Settings on the pane where the user can turn access on. */
	openPrivacySettings: (pane: PrivacyPane) => typedError<null, string>(__TAURI_INVOKE("open_privacy_settings", { pane })),
	/**
	 *  The onboarding's 10 s test: records briefly and deletes the meeting
	 *  afterwards; returns its id so the UI can follow its events.
	 */
	testCapture: (seconds: number) => typedError<string, string>(__TAURI_INVOKE("test_capture", { seconds })),
	modelsStatus: () => typedError<ModelsStatus, string>(__TAURI_INVOKE("models_status")),
	/**
	 *  Downloads every missing model of this machine's tier, one after another,
	 *  in the background (`modelDownload` events). A second call while running
	 *  does nothing.
	 */
	downloadModels: () => typedError<null, string>(__TAURI_INVOKE("download_models")),
	/**  Stops the download (the partial file stays; the next download resumes). */
	cancelModelDownload: () => __TAURI_INVOKE<void>("cancel_model_download"),
	getSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("get_settings")),
	/**  Changes some settings and returns them all. */
	updateSettings: (patch: SettingsPatch) => typedError<AppSettings, string>(__TAURI_INVOKE("update_settings", { patch })),
	micPermission: () => __TAURI_INVOKE<Permission>("mic_permission"),
	/**  Shows the OS prompt when undetermined (blocks until answered). */
	requestMicPermission: () => typedError<Permission, string>(__TAURI_INVOKE("request_mic_permission")),
	replyMeetingDetected: (app: string, reply: DetectReply) => typedError<null, string>(__TAURI_INVOKE("reply_meeting_detected", { app, reply })),
	/**
	 *  A token for `ghi-audio://localhost/<token>` (build the URL with
	 *  `convertFileSrc(token, "ghi-audio")`). `track`: 0 mic, 1 system; default
	 *  is the diarized track (system in a call, else the mic).
	 */
	issueAudioSample: (meeting: string, t0Ms: number | null, t1Ms: number | null, track: number | null) => typedError<string, string>(__TAURI_INVOKE("issue_audio_sample", { meeting, t0Ms, t1Ms, track })),
	/**
	 *  Brings the main window forward on `route` (a hash route, e.g. `/live`).
	 *  Async: creating a window from a sync command deadlocks on Windows.
	 */
	showMain: (route: string | null) => typedError<null, string>(__TAURI_INVOKE("show_main", { route })),
	hidePopover: () => __TAURI_INVOKE<void>("hide_popover"),
	/**  The mini-recorder as a full card or a small pill. */
	setMiniCompact: (compact: boolean) => typedError<null, string>(__TAURI_INVOKE("set_mini_compact", { compact })),
	closeMini: () => __TAURI_INVOKE<void>("close_mini"),
	/**  Opens the mini-recorder from the live view ("Mini recorder"). */
	openMiniRecorder: () => __TAURI_INVOKE<void>("open_mini_recorder"),
	closeDetect: () => __TAURI_INVOKE<void>("close_detect"),
	meetingDetail: (meeting: string) => typedError<MeetingDetail, string>(__TAURI_INVOKE("meeting_detail", { meeting })),
	meetingNotes: (meeting: string) => typedError<MeetingNotes, string>(__TAURI_INVOKE("meeting_notes", { meeting })),
	meetingTranscript: (meeting: string) => typedError<MeetingTranscript, string>(__TAURI_INVOKE("meeting_transcript", { meeting })),
	/**  Corrects a transcript line ("Edited"; the final pass keeps it). */
	updateSegmentText: (meeting: string, segment: string, text: string) => typedError<null, string>(__TAURI_INVOKE("update_segment_text", { meeting, segment, text })),
	/**  Moves a transcript line to another speaker of the meeting. */
	setSegmentSpeaker: (meeting: string, segment: string, speaker: string) => typedError<null, string>(__TAURI_INVOKE("set_segment_speaker", { meeting, segment, speaker })),
	/**  Edits a note block (an AI block becomes the user's: `aiEdited`). */
	updateNoteBlock: (meeting: string, block: string, text: string) => typedError<null, string>(__TAURI_INVOKE("update_note_block", { meeting, block, text })),
	diagnosticsStatus: () => __TAURI_INVOKE<DiagnosticsStatus>("diagnostics_status"),
	/**  Opens the diagnostics folder in Finder. */
	revealDiagnostics: () => typedError<null, string>(__TAURI_INVOKE("reveal_diagnostics")),
	/**  The user saw the crash notice: it does not show again this launch. */
	acknowledgeCrash: () => __TAURI_INVOKE<void>("acknowledge_crash"),
	/**  Adds one of the user's own notes ("My notes"). */
	addNoteBlock: (meeting: string, text: string) => typedError<NoteBlockView, string>(__TAURI_INVOKE("add_note_block", { meeting, text })),
	deleteNoteBlock: (meeting: string, block: string) => typedError<null, string>(__TAURI_INVOKE("delete_note_block", { meeting, block })),
	addActionItem: (meeting: string, text: string, owner: string | null) => typedError<ActionItemView, string>(__TAURI_INVOKE("add_action_item", { meeting, text, owner })),
	updateActionItem: (meeting: string, item: string, text: string) => typedError<null, string>(__TAURI_INVOKE("update_action_item", { meeting, item, text })),
	setActionDone: (meeting: string, item: string, done: boolean) => typedError<null, string>(__TAURI_INVOKE("set_action_done", { meeting, item, done })),
	/**  Sets (or clears) who owns an action item: one of the meeting's speakers. */
	setActionOwner: (meeting: string, item: string, owner: string | null) => typedError<null, string>(__TAURI_INVOKE("set_action_owner", { meeting, item, owner })),
	deleteActionItem: (meeting: string, item: string) => typedError<null, string>(__TAURI_INVOKE("delete_action_item", { meeting, item })),
	/**  The built-in notes templates, in menu order. */
	listTemplates: () => __TAURI_INVOKE<TemplateInfo[]>("list_templates"),
	/**
	 *  Rewrites the AI notes (template and language as chosen); what the user
	 *  wrote, edited, pinned or ticked off stays [RT-7]. Returns whether it waits
	 *  for the local model to be installed.
	 */
	regenerateNotes: (meeting: string, template: string | null, language: NotesLanguage) => typedError<boolean, string>(__TAURI_INVOKE("regenerate_notes", { meeting, template, language })),
	/**  Accent-insensitive search over transcripts and notes (VN-folded). */
	searchMeetings: (request: SearchRequest) => typedError<SearchResults, string>(__TAURI_INVOKE("search_meetings", { request })),
	/**  Plays the whole meeting (the open one; any earlier play token stops working). */
	issueAudioPlay: (meeting: string) => typedError<AudioPlay, string>(__TAURI_INVOKE("issue_audio_play", { meeting })),
	/**
	 *  The waveform of a finished meeting (computed once, then kept sealed in
	 *  the store until the audio goes).
	 */
	waveformPeaks: (meeting: string) => typedError<Waveform, string>(__TAURI_INVOKE("waveform_peaks", { meeting })),
	/**
	 *  Saves one meeting (a save dialog first). Returns the file name, or `None`
	 *  if the user cancelled.
	 */
	exportMeeting: (meeting: string, format: ExportFormat, content: ExportContent) => typedError<string | null, string>(__TAURI_INVOKE("export_meeting", { meeting, format, content })),
	/**
	 *  Saves several meetings into a folder (one file each). Returns how many
	 *  were written, or `None` if the user cancelled.
	 */
	exportMeetings: (meetings: string[], format: ExportFormat, content: ExportContent, title: string) => typedError<number | null, string>(__TAURI_INVOKE("export_meetings", { meetings, format, content, title })),
	/**
	 *  Writes the meeting as a note into an Obsidian vault folder (chosen once,
	 *  then remembered; `chooseFolder` asks again). Returns the note's name, or
	 *  `None` if the user cancelled.
	 */
	exportObsidian: (meeting: string, content: ExportContent, chooseFolder: boolean, title: string) => typedError<string | null, string>(__TAURI_INVOKE("export_obsidian", { meeting, content, chooseFolder, title })),
	/**  The meeting as Markdown or plain text, for the clipboard. */
	meetingAsText: (meeting: string, markdown: boolean, content: ExportContent) => typedError<string, string>(__TAURI_INVOKE("meeting_as_text", { meeting, markdown, content })),
	/**  Shows the last exported file in Finder. */
	revealLastExport: () => typedError<null, string>(__TAURI_INVOKE("reveal_last_export")),
	/**  The open dialog: stages the chosen files. */
	pickImportFiles: (title: string) => typedError<StagedFile[], string>(__TAURI_INVOKE("pick_import_files", { title })),
	/**  What was staged by a drop (the event carries ids only). */
	stagedFiles: (ids: string[]) => __TAURI_INVOKE<StagedFile[]>("staged_files", { ids }),
	/**  Removes files from the staging list. */
	unstageFiles: (ids: string[]) => __TAURI_INVOKE<void>("unstage_files", { ids }),
	/**  Queues staged files for import (unsupported or empty ones are refused). */
	startImport: (ids: string[], choice: ImportChoice) => typedError<null, string>(__TAURI_INVOKE("start_import", { ids, choice })),
	/**  Stops a queued or running import (its half-made meeting is removed). */
	cancelImport: (id: string) => __TAURI_INVOKE<void>("cancel_import", { id }),
	/**  Which providers have a key (never the key). */
	cloudKeys: () => typedError<ProviderKey[], string>(__TAURI_INVOKE("cloud_keys")),
	/**  Stores a provider's API key in the Keychain (from a masked field). */
	setCloudKey: (provider: string, key: string) => typedError<null, string>(__TAURI_INVOKE("set_cloud_key", { provider, key })),
	deleteCloudKey: (provider: string) => typedError<null, string>(__TAURI_INVOKE("delete_cloud_key", { provider })),
	/**  The models with a known price, per provider (the sheet's menus). */
	cloudModels: () => __TAURI_INVOKE<CloudModel[]>("cloud_models"),
	/**  Builds the exact request for the sheet (nothing is sent). */
	cloudPreview: (meeting: string, ask: CloudAsk) => typedError<CloudPreviewResult, string>(__TAURI_INVOKE("cloud_preview", { meeting, ask })),
	/**  Sends the previewed request, exactly. */
	cloudSend: (id: string) => typedError<CloudSendResult, string>(__TAURI_INVOKE("cloud_send", { id })),
	/**  "Never send to cloud" for a meeting. */
	setMeetingCloudLocked: (meeting: string, locked: boolean) => typedError<null, string>(__TAURI_INVOKE("set_meeting_cloud_locked", { meeting, locked })),
	/**  Every cloud request made, newest first (no content is kept). */
	cloudRequestLog: (limit: number) => typedError<CloudLogEntry[], string>(__TAURI_INVOKE("cloud_request_log", { limit })),
	/**  Ask this meeting, answered on this device by the local model. */
	askMeeting: (meeting: string, question: string, language: NotesLanguage) => typedError<AskAnswer, string>(__TAURI_INVOKE("ask_meeting", { meeting, question, language })),
	vocabulary: () => typedError<Vocabulary, string>(__TAURI_INVOKE("vocabulary")),
	/**  Replaces the user's terms (trimmed, deduplicated, at most 200). */
	setVocabulary: (terms: string[]) => typedError<Vocabulary, string>(__TAURI_INVOKE("set_vocabulary", { terms })),
	/**  Removes a learned name from the vocabulary (it stays removed). */
	ignoreLearnedTerm: (term: string) => typedError<Vocabulary, string>(__TAURI_INVOKE("ignore_learned_term", { term })),
	/**
	 *  "Export everything": every meeting with its audio in one archive,
	 *  encrypted with `password` (a save dialog first). Returns the file name, or
	 *  `None` if the user cancelled.
	 */
	exportEverything: (password: string) => typedError<string | null, string>(__TAURI_INVOKE("export_everything", { password })),
	/**
	 *  "Delete all data": everything goes (meetings, audio, keys, settings),
	 *  then the app restarts into onboarding. The UI asks for a typed
	 *  confirmation first.
	 */
	deleteAllData: () => typedError<null, string>(__TAURI_INVOKE("delete_all_data")),
	/**  Files staged by a drop that the import screen hasn't shown yet (read once). */
	takeDroppedFiles: () => __TAURI_INVOKE<StagedFile[]>("take_dropped_files"),
	/**
	 *  A follow-up email from the meeting's notes, written on this device (to
	 *  edit and copy; nothing is sent).
	 */
	draftFollowupEmail: (meeting: string, language: NotesLanguage, tone: EmailTone) => typedError<EmailDraft, string>(__TAURI_INVOKE("draft_followup_email", { meeting, language, tone })),
	updateStatus: () => __TAURI_INVOKE<UpdateStatus>("update_status"),
	/**
	 *  "Check for updates" (works with automatic checks off, not under strict
	 *  offline).
	 */
	checkForUpdates: () => typedError<UpdateStatus, string>(__TAURI_INVOKE("check_for_updates")),
	/**  "Restart to update": swaps in the downloaded version and relaunches. */
	installUpdate: () => typedError<null, string>(__TAURI_INVOKE("install_update")),
	/**
	 *  A system notification (notes ready, recovered); clicking it brings the
	 *  app forward. The text comes localized from the UI.
	 */
	showNotification: (title: string, body: string) => typedError<null, string>(__TAURI_INVOKE("show_notification", { title, body })),
};

/** Events */
export const events = {
	coreEvent: makeEvent<CoreEvent>("core-event"),
	importStaged: makeEvent<ImportStaged>("import-staged"),
	importUpdate: makeEvent<ImportUpdate>("import-update"),
	meetingDetected: makeEvent<MeetingDetected>("meeting-detected"),
	menuAction: makeEvent<MenuAction>("menu-action"),
	modelDownload: makeEvent<ModelDownload>("model-download"),
	navigate: makeEvent<Navigate>("navigate"),
	quitRequested: makeEvent<QuitRequested>("quit-requested"),
	updateChanged: makeEvent<UpdateChanged>("update-changed"),
};

/* Types */
export type ActionItemView = {
	gid: string,
	text: string,
	ownerSpeakerGid: string | null,
	/**  The due date as spoken ("thứ Sáu"). */
	dueText: string | null,
	done: boolean,
	origin: Origin,
	citations: Citation[],
};

/**
 *  App settings the UI reads (stored in the encrypted store). Every field is
 *  required in the TypeScript type; what the store lacks takes its default.
 */
export type AppSettings = {
	/**  Onboarding finished (or skipped). */
	onboardingDone: boolean,
	/**  Ask to record when a meeting app starts using the mic. */
	detectMeetings: boolean,
	/**  ⌘M / Ctrl+M marks a moment from any app while recording. */
	globalMarkShortcut: boolean,
	/**  ⌘⇧R / Ctrl+Shift+R starts or stops recording from any app. */
	globalRecordShortcut: boolean,
	/**
	 *  Voice profile of the user ("Me"). Off until speaker embeddings exist
	 *  (phase 14); the onboarding step is hidden while off.
	 */
	voiceProfilesMe: boolean,
	/**  Saving other people's voices (consent dialog). Off for the alpha. */
	voiceProfilesThirdParty: boolean,
	/**  No network at all, model downloads included (doc 02 §L). */
	strictOffline: boolean,
	/**  Language of new meetings: `en`, `vi`, or `auto` (both, code-switching). */
	meetingLanguage: MeetingLanguage,
	/**
	 *  The cloud provider and model the send sheet starts with (empty: none
	 *  chosen yet). Every send is still previewed and confirmed.
	 */
	cloudProvider: string,
	cloudModel: string,
	/**  Hide names and personal data from cloud requests (restored locally). */
	cloudRedact: boolean,
	/**  Days to keep meeting audio (0: until the meeting is deleted). */
	audioRetentionDays: number,
	/**
	 *  The consent message to share at the start of a meeting (empty: the
	 *  built-in text in the app's language).
	 */
	consentMessageEn: string,
	consentMessageVi: string,
	/**  Check for app updates at launch and daily (never under strict offline). */
	updateCheck: boolean,
};

/**  Versions shown in Settings → About. */
export type AppVersion = {
	app: string,
	core: string,
};

/**  An answer to "Ask this meeting". */
export type AskAnswer = {
	/**  False: "Not discussed in this meeting". */
	answered: boolean,
	text: string,
	citations: Citation[],
	/**  The terms looked for (not discussed). */
	searched: string[],
	/**  `local` or the cloud provider. */
	engine: string,
};

/**  The audio bar's source: a play token and how long the audio is. */
export type AudioPlay = {
	token: string,
	durationMs: number | null,
};

/**  A citation resolved against the current transcript. */
export type Citation = {
	t0Ms: number | null,
	t1Ms: number | null,
	/**  The cited words (overlapping segments, shortened). */
	quote: string,
	speakerGid: string | null,
	/**  Made against an older transcript (the text was found by time). */
	stale: boolean,
	/**  Nothing in the transcript at that time ("not found"). */
	missing: boolean,
};

export type CloudAsk = {
	provider: string,
	model: string,
	task: CloudTask,
	/**  Replace names and personal data with placeholders (restored locally). */
	redact: boolean,
	/**  More names to hide besides the speakers'. */
	extraNames: string[],
};

export type CloudLogEntry = {
	meeting: string,
	meetingTitle: string,
	provider: string,
	model: string,
	tokensIn: number | null,
	tokensOut: number | null,
	/**  Unix ms. */
	at: number | null,
};

export type CloudModel = {
	provider: string,
	model: string,
};

/**  The send preview the sheet shows (nothing has left the device). */
export type CloudPreview = {
	/**  Confirm with `cloud_send(id)`. */
	id: string,
	provider: string,
	model: string,
	host: string,
	/**  The request body, byte for byte. */
	payload: string,
	sha256: string,
	tokensEst: number,
	costEstUsd: number | null,
	retentionNote: string,
	/**  Things in the text that still look like personal data. */
	warnings: string[],
	redactions: Redaction[],
};

export type CloudPreviewResult = {
	kind: "preview",
} & CloudPreview | 
/**  An Ask that nothing matched: answered without any request. */
{
	kind: "answer",
} & AskAnswer;

export type CloudSendResult = 
/**  The notes were rewritten (what the user wrote stays). */
({ kind: "notes" }) & { leftDevice?: never; reason?: never } | {
	kind: "answer",
} & AskAnswer | 
/**
 *  The provider failed: notes are being written on this device instead
 *  (an Ask is answered on this device by the caller).
 */
{ kind: "failed"; reason: string; 
/**  The request may have left the device (it is in the request log). */
leftDevice: boolean };

export type CloudTask = 
/**  Rewrite the notes ("Improve with cloud…"). */
{ kind: "notes"; template: string | null; language: NotesLanguage } | 
/**  Ask this meeting. */
{ kind: "ask"; question: string; language: NotesLanguage };

/**  Every core event, in order (`seq` is gap-free; on a gap, re-read state). */
export type CoreEvent = Envelope;

/**  The user's answer to a detection prompt. */
export type DetectReply = 
/**  Recording starts (the UI calls start_recording itself). */
"start" | 
/**  Quiet for this call (the 30 min cooldown already applies). */
"notNow" | 
/**  Never ask for this app again. */
"never";

export type DiagnosticsStatus = {
	crashedLastRun: boolean,
	reports: number,
};

/**  What "discard the last N seconds" would remove, shown before confirming [RT-1]. */
export type DiscardPreview = {
	/**  Where the cut lands (meeting ms). */
	fromMs: number | null,
	/**  Transcript lines that end after the cut. */
	lines: string[],
	/**  Notepad lines typed after the cut. */
	notes: string[],
	marks: number,
};

export type DownloadPhase = "downloading" | 
/**  Checking the SHA-256 of the finished file. */
"verifying" | "done" | "failed" | "cancelled";

export type DuplicateOf = {
	meeting: string,
	title: string,
};

export type EmailDraft = {
	subject: string,
	body: string,
};

export type EmailTone = "friendly" | "neutral" | "formal";

/**
 *  An event with its sequence number (gap-free per bus) and wall time, so a
 *  late subscriber (a reloaded webview) can tell what it missed.
 */
export type Envelope = {
	seq: number | null,
	/**  Unix ms. */
	atMs: number | null,
	event: Event,
};

export type ErrorKind = "permission" | "capture" | "engine" | "modelsMissing" | "storage" | "job";

export type Event = { type: "stateChanged"; meeting: string; state: SessionState } | 
/**
 *  Sent once when a session reaches Recording, right before the
 *  `StateChanged { Recording }` that follows it. `mode` is "call" or
 *  "room" as recorded (a call without system audio is a room).
 */
{ type: "sessionStarted"; meeting: string; mode: string; language: string | null; title: string } | { type: "transcriptPartial"; meeting: string; 
/**  0 = mic, 1 = system. */
track: number; text: string } | { type: "transcriptFinal"; meeting: string; line: LineInfo } | { type: "speakerArrived"; meeting: string; speaker: SpeakerInfo } | 
/**  A provisional speaker became "Speaker N". */
{ type: "speakerConfirmed"; meeting: string; speaker: SpeakerInfo } | { type: "speakerRenamed"; meeting: string; speaker: SpeakerInfo } | { type: "speakersMerged"; meeting: string; from: number; into: number } | 
/**
 *  `lines`: segment gids moved from `from` to the new speaker (each once).
 *  If the store refuses the move, an `Error` event follows and the lines
 *  stay with `from`.
 */
{ type: "speakerSplit"; meeting: string; from: number; speaker: SpeakerInfo; lines: string[] } | { type: "speakerNotAPerson"; meeting: string; id: number } | { type: "markAdded"; meeting: string; tMs: number | null } | 
/**  Everything from `from_ms` on was removed (audio, lines, marks, notes). */
{ type: "discardApplied"; meeting: string; fromMs: number | null } | 
/**
 *  RMS level of each track over the last ~100 ms (at most 10 per second,
 *  only while audio flows). `None`: the track is not captured or no audio
 *  passed in the window (paused, asleep); digital silence reads -100.
 */
{ type: "levelMeter"; meeting: string; micDbfs: number | null; systemDbfs: number | null } | 
/**
 *  The Mac went to sleep; the timeline stops (the gap is not recorded as
 *  audio) until `Woke` [RT-10].
 */
{ type: "slept"; meeting: string } | { type: "woke"; meeting: string } | 
/**  The system-audio tap was restarted (an output device change). */
{ type: "systemAudioRestarted"; meeting: string } | 
/**
 *  The system track has been digital silence for `silent_s` seconds in a
 *  call: a denied or broken tap (hint: record the room instead).
 */
{ type: "silentSystemTrack"; meeting: string; silentS: number | null } | { type: "diskLow"; meeting: string; freeBytes: number | null } | { type: "diskFull"; meeting: string } | 
/**  A capture device vanished (0 = mic, 1 = system). */
{ type: "trackLost"; meeting: string; track: number } | 
/**
 *  The audio route changed; `bluetooth_hfp`: the input is a Bluetooth
 *  headset, whose mic drops the whole link to call quality.
 */
{ type: "routeChanged"; meeting: string; bluetoothHfp: boolean } | { type: "health"; meeting: string; 
/**  Seconds the live transcript trails the audio. */
asrLagS: number | null; 
/**  Audio skipped by ASR so far (seconds; the final pass fills it). */
asrSkippedS: number | null; aec: boolean } | { type: "jobProgress"; meeting: string | null; job: number | null; kind: string; stage: Stage | null; 
/**  0..1 within the job. */
progress: number | null } | { type: "notesReady"; meeting: string; 
/**  1 = from the live transcript, 2 = after the final pass. */
version: number } | { type: "error"; meeting: string | null; kind: ErrorKind; message: string };

/**  What goes into the file; headings in the app's language. */
export type ExportContent = {
	notes: boolean,
	transcript: boolean,
	/**  Headings in Vietnamese (else English). */
	vietnamese: boolean,
};

export type ExportFormat = "markdown" | "text" | "srt" | "vtt" | "docx";

export type ImportChoice = {
	/**  The transcript language (`en`, `vi`), or detect. */
	language: string | null,
	/**  Keep a stereo file's two channels as you / the others. */
	splitChannels: boolean,
};

export type ImportProblem = 
/**  Not audio we can read. */
"unsupported" | 
/**  An empty file. */
"empty" | 
/**  Over 4 hours: allowed, with a warning. */
"veryLong" | 
/**  Imported before (see `duplicateOf`). */
"duplicate";

export type ImportSource = "plaud" | "zoom" | "teams" | "voiceMemos" | "other";

/**  Files dropped on the window or the Dock icon were staged. */
export type ImportStaged = {
	files: StagedFileEvent[],
};

export type ImportState = "queued" | "decoding" | "done" | "failed" | "cancelled";

/**  One step of a queued import. */
export type ImportUpdate = {
	id: string,
	state: ImportState,
	/**  The meeting being made (once decoding started). */
	meeting: string | null,
	/**  0..1 while decoding. */
	progress: number | null,
	error: string | null,
};

/**  A final transcript line. */
export type LineInfo = {
	/**  Store segment gid (empty until persisted). */
	gid: string,
	speaker: number | null,
	t0Ms: number | null,
	t1Ms: number | null,
	text: string,
	/**  Two speakers talked over each other. */
	overlap: boolean,
	words: WordInfo[],
};

export type MarkView = {
	tMs: number | null,
	/**  `mark`, `decision`, `action`, `question`. */
	tag: string,
};

export type MeetingDetail = {
	gid: string,
	title: string,
	/**  Unix ms. */
	startedAt: number | null,
	durationMs: number | null,
	/**  `live`, `import`, … */
	source: string,
	/**  `call` or `room`. */
	mode: string,
	/**  The transcript's language (`en`, `vi`, `mixed`), if known. */
	language: string | null,
	/**  Notes template id (`None`: the default, `general`). */
	template: string | null,
	status: string,
	cloudLocked: boolean,
	sensitive: boolean,
	cloudUsed: boolean,
	consentConfirmed: boolean,
	transcriptVersion: number | null,
	/**  Some audio is kept (retention may have removed it). */
	audioAvailable: boolean,
	speakers: MeetingSpeaker[],
	job: MeetingJob | null,
};

/**  A meeting app started using the microphone. */
export type MeetingDetected = {
	/**  Stable app key (`zoom`, `teams`, `chrome`, …), for the reply. */
	app: string,
	/**  Shown in the prompt ("Zoom"); browsers prompt generically. */
	appName: string,
	browser: boolean,
};

/**  What the library shows about a meeting's processing. */
export type MeetingJob = {
	/**  `notes_live`, `final_pass`, `notes_final`. */
	kind: string,
	/**  0..1. */
	progress: number | null,
	/**  Queued until its models are installed (record now, process later). */
	waitingForModels: boolean,
};

export type MeetingLanguage = "en" | "vi" | "auto";

export type MeetingNotes = {
	blocks: NoteBlockView[],
	actionItems: ActionItemView[],
	/**  The meeting template's own sections (for `section:<id>` blocks). */
	sections: TemplateSection[],
};

export type MeetingRow = {
	gid: string,
	title: string,
	/**  Unix ms. */
	startedAt: number | null,
	durationMs: number | null,
	/**  `live`, `import`, … */
	source: string,
	/**  `call` or `room`. */
	mode: string,
	/**  `recording`, `done`, `processing`, `ready`, … */
	status: string,
	transcriptVersion: number | null,
	cloudUsed: boolean,
	consentConfirmed: boolean,
	/**  Notes template id (`None`: the default). */
	template: string | null,
	/**  Named speakers, for the people column and filter. */
	people: PersonChip[],
	/**  The active job, if any. */
	job: MeetingJob | null,
};

export type MeetingSpeaker = {
	gid: string,
	/**  The user's name for them, if any. */
	name: string | null,
	/**  1-based number shown as "Speaker N" while unnamed. */
	number: number,
	/**  Palette slot 1..8 (0: Others). */
	colorSlot: number,
	isMe: boolean,
	notPerson: boolean,
	lines: number,
	/**  A span of their speech for the sample (meeting ms, at most 3 s). */
	sampleT0Ms: number | null,
	sampleT1Ms: number | null,
};

export type MeetingTranscript = {
	version: number | null,
	segments: SegmentView[],
	marks: MarkView[],
	/**  Topic headers (from the notes), in time order. */
	topics: TopicView[],
};

/**  A menu command for the UI. */
export type MenuAction = 
/**  ⌘⇧R: start or stop recording. */
"toggleRecording" | 
/**  ⌘M: mark this moment. */
"mark" | 
/**  ⌘K: command palette. */
"commandPalette" | 
/**  ⌘,: settings. */
"settings";

/**  Download progress for one model. */
export type ModelDownload = {
	model: string,
	phase: DownloadPhase,
	done: number | null,
	total: number | null,
	/**  Why it stopped (failed). */
	error: string | null,
};

export type ModelInfo = {
	id: string,
	/**  `asr`, `diarization`, `llm`. */
	role: string,
	size: number | null,
	installed: boolean,
	/**  Bytes of an unfinished download (resumes from here). */
	partialBytes: number | null,
	/**  Failed its SHA-256 at load: download it again (D12). */
	damaged: boolean,
};

export type ModelsStatus = {
	/**  `light`, `balanced` or `max` (hardware tier). */
	tier: string,
	models: ModelInfo[],
	downloading: boolean,
};

/**  The UI should go to `route` (a window was brought forward for it). */
export type Navigate = {
	route: string,
};

export type NoteBlockView = {
	gid: string,
	/**
	 *  `tldr`, `decision`, `question`, `quote`, `topic`, `section:<id>`,
	 *  `enhanced:<user block gid>` (the AI's expansion of a user note; an
	 *  empty text means "not found"), or the user's `note` / `decision` /
	 *  `action` / `question`.
	 */
	kind: string,
	origin: Origin,
	text: string,
	pinned: boolean,
	citations: Citation[],
};

/**  The kinds a user line can carry (in-call tags feed the notes, brief D4). */
export type NoteKind = "note" | "decision" | "action" | "question";

/**  A line of the live notepad (a user note block at a point in meeting time). */
export type NoteLine = {
	gid: string,
	text: string,
	/**  Meeting time the line was typed at (ms), if anchored. */
	tMs: number | null,
	/**  `note` (typed), `decision`, `action`, `question` (tagged). */
	kind: string,
};

/**  The language notes are written in. */
export type NotesLanguage = 
/**  The meeting's own (dominant) language. */
"meeting" | "en" | "vi";

export type Origin = "user" | "ai" | 
/**  AI-written, then changed by the user (kept by a regenerate). */
"aiEdited";

/**  Microphone access as macOS reports it. */
export type Permission = "granted" | "denied" | 
/**  Not asked yet. */
"undetermined" | 
/**  Blocked by a policy (MDM, parental controls). */
"restricted" | 
/**  Not applicable on this platform (no macOS permission model). */
"unsupported";

/**  A named speaker as a chip: color + initial (never color alone). */
export type PersonChip = {
	name: string,
	/**  Palette slot 1..8 (0: Others). */
	colorSlot: number,
};

/**  A pane of the OS privacy settings, for a denied permission. */
export type PrivacyPane = "microphone" | 
/**  "Screen & System Audio Recording" on macOS. */
"systemAudio" | "notifications";

export type ProviderKey = {
	provider: string,
	stored: boolean,
};

/**
 *  The user quit while recording: the UI asks "Stop and quit?" and answers
 *  with `quit_app`.
 */
export type QuitRequested = Record<string, never>;

/**  Recording mode (doc 02 §A). */
export type RecordMode = 
/**  Mic (you) + the call's audio. */
"call" | 
/**  One mic in a room. */
"room";

/**  A meeting closed by crash recovery at this launch. */
export type RecoveredMeeting = {
	gid: string,
	title: string,
	/**  What was saved (ms). */
	durationMs: number | null,
};

export type Redaction = {
	kind: string,
	count: number,
};

export type SearchHitView = {
	/**  `segment` or `note`. */
	kind: string,
	meeting: string,
	meetingTitle: string,
	meetingStartedAt: number | null,
	/**  Segment or note block gid. */
	item: string,
	speakerGid: string | null,
	t0Ms: number | null,
	t1Ms: number | null,
	snippet: string,
	/**  `[start, end)` in UTF-16 code units of `snippet` (JS string indexes). */
	highlights: ([number, number])[],
	/**  The accented query matched exactly (ranked first). */
	exact: boolean,
};

export type SearchRequest = {
	text: string,
	/**  `live` or `file`. */
	source: string | null,
	template: string | null,
	/**  Meeting start range, unix ms, inclusive. */
	fromMs: number | null,
	toMs: number | null,
	/**  Only this meeting ("Find" inside a meeting uses the transcript instead). */
	meeting: string | null,
	limit: number,
	offset: number,
};

export type SearchResults = {
	hits: SearchHitView[],
	/**  More matches exist than were considered. */
	truncated: boolean,
};

export type SegmentView = {
	gid: string,
	speakerGid: string | null,
	t0Ms: number | null,
	t1Ms: number | null,
	text: string,
	language: string | null,
	confidence: number | null,
	/**  The user changed the text ("Edited"). */
	edited: boolean,
	/**
	 *  One per space-separated word of `text`, in order (empty when the
	 *  counts don't match, e.g. after an edit).
	 */
	words: WordTiming[],
};

/**
 *  Everything a reloaded webview needs to redraw a running session. `seq` is
 *  the bus sequence number read before the rest was gathered: events with a
 *  greater `seq` may repeat what is here (lines are told apart by `gid`).
 */
export type SessionSnapshot = {
	seq: number | null,
	meeting: string,
	state: SessionState,
	nowMs: number | null,
	/**  A live transcript is being made (false: models missing). */
	transcribing: boolean,
	/**  "call" or "room" (after the call-without-system-audio fallback). */
	mode: string,
	language: string | null,
	title: string,
	/**  Everyone's consent to recording was confirmed (the live toggle). */
	consentConfirmed: boolean,
	/**  Speakers still in play (merged ones are gone). */
	speakers: SpeakerInfo[],
	/**  Final lines stored so far, in time order. */
	lines: LineInfo[],
	/**  Marks (ms), in time order. */
	marks: (number | null)[],
};

/**  SessionManager states (brief §7, the Record control). */
export type SessionState = "idle" | "starting" | "recording" | "paused" | "stopping" | "processing" | "ready" | "failed";

/**  A change to some settings; fields left out keep their value. */
export type SettingsPatch = {
	onboardingDone?: boolean | null,
	detectMeetings?: boolean | null,
	globalMarkShortcut?: boolean | null,
	globalRecordShortcut?: boolean | null,
	strictOffline?: boolean | null,
	meetingLanguage?: MeetingLanguage | null,
	cloudProvider?: string | null,
	cloudModel?: string | null,
	cloudRedact?: boolean | null,
	audioRetentionDays?: number | null,
	consentMessageEn?: string | null,
	consentMessageVi?: string | null,
	updateCheck?: boolean | null,
};

export type SpeakerInfo = {
	/**  Session speaker id (stable for the meeting). */
	id: number,
	/**  What the UI shows: a name, "Me", "Speaker N" or "Identifying…". */
	label: string,
	/**  1..=8, or 0 for the shared Others lane. */
	colorSlot: number,
	isMe: boolean,
	provisional: boolean,
	notPerson: boolean,
	others: boolean,
};

/**  Final-pass stages, in order (shown as progress in the UI). */
export type Stage = "decoding" | "refiningSpeakers" | "matchingVoices" | "improvingTranscript" | "writingNotes";

export type StagedFile = {
	id: string,
	name: string,
	sizeBytes: number | null,
	durationMs: number | null,
	/**  Two or more: "split channels" is offered (a Zoom/Teams stereo file). */
	channels: number,
	source: ImportSource,
	problems: ImportProblem[],
	duplicateOf: DuplicateOf | null,
};

/**  [`StagedFile`] as carried by an event (events need `Deserialize`). */
export type StagedFileEvent = {
	id: string,
};

export type Stopped = {
	meeting: string,
	durationMs: number | null,
};

export type TemplateInfo = {
	id: string,
	name: string,
	sections: TemplateSection[],
};

export type TemplateSection = {
	id: string,
	titleEn: string,
	titleVi: string,
};

export type TopicView = {
	title: string,
	tMs: number | null,
};

/**  The status changed (the About section and a banner follow it). */
export type UpdateChanged = {
	status: UpdateStatus,
};

export type UpdateStatus = {
	/**  This build can update itself (a feed and a key are built in). */
	configured: boolean,
	checking: boolean,
	/**  Unix ms of the last successful check. */
	lastCheck: number | null,
	/**  A newer version, if any. */
	available: string | null,
	notesUrl: string | null,
	/**  Downloaded and checked: "Restart to update" can run. */
	ready: boolean,
	/**  The running version was withdrawn: update now. */
	runningPulled: boolean,
	/**  Too old to update in place: download the new version. */
	reinstallNeeded: boolean,
	error: string | null,
};

export type Vocabulary = {
	/**  The user's own terms (names, products, jargon), as written. */
	terms: string[],
	/**  Names learned from the speakers the user named (removable). */
	learned: string[],
	maxTerms: number,
};

/**  The audio bar's waveform. */
export type Waveform = {
	perSecond: number,
	/**  Loudness 0..255 per bucket, from the start of the meeting. */
	peaks: number[],
};

export type WordInfo = {
	text: string,
	t0Ms: number | null,
	t1Ms: number | null,
	lowConfidence: boolean,
};

export type WordTiming = {
	t0Ms: number | null,
	t1Ms: number | null,
	/**  0..1, if the engine gave one. */
	confidence: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

