// SPDX-License-Identifier: Apache-2.0

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appVersion: () => __TAURI_INVOKE<AppVersion>("app_version"),
	startRecording: (mode: RecordMode, language: string | null, title: string) => typedError<string, string>(__TAURI_INVOKE("start_recording", { mode, language, title })),
	stopRecording: () => typedError<Stopped, string>(__TAURI_INVOKE("stop_recording")),
	pauseRecording: () => typedError<null, string>(__TAURI_INVOKE("pause_recording")),
	resumeRecording: () => typedError<null, string>(__TAURI_INVOKE("resume_recording")),
	/**  Marks this moment; returns its meeting time (ms). */
	markMoment: () => typedError<number | null, string>(__TAURI_INVOKE("mark_moment")),
	/**  Discards the last `seconds` [RT-1]; returns where the cut landed (ms). */
	discardLast: (seconds: number | null) => typedError<number | null, string>(__TAURI_INVOKE("discard_last", { seconds })),
	renameSpeaker: (id: number, name: string) => typedError<null, string>(__TAURI_INVOKE("rename_speaker", { id, name })),
	mergeSpeakers: (from: number, into: number) => typedError<null, string>(__TAURI_INVOKE("merge_speakers", { from, into })),
	/**  Moves the given lines (segment gids) to a new speaker; returns its id. */
	splitSpeaker: (from: number, lines: string[]) => typedError<number | null, string>(__TAURI_INVOKE("split_speaker", { from, lines })),
	speakerNotAPerson: (id: number) => typedError<null, string>(__TAURI_INVOKE("speaker_not_a_person", { id })),
	/**  Imports an audio/video file as a meeting (transcribed by the job runner). */
	importRecording: (path: string, splitChannels: boolean) => typedError<Imported, string>(__TAURI_INVOKE("import_recording", { path, splitChannels })),
};

/** Events */
export const events = {
	coreEvent: makeEvent<CoreEvent>("core-event"),
};

/* Types */
/**  Versions shown in Settings → About. */
export type AppVersion = {
	app: string,
	core: string,
};

/**  Every core event, in order (`seq` is gap-free; on a gap, re-read state). */
export type CoreEvent = Envelope;

/**
 *  An event with its sequence number (gap-free per bus) and wall time, so a
 *  late subscriber (a reloaded webview) can tell what it missed.
 */
export type Envelope = {
	seq: number | null,
	/**  Unix ms. */
	atMs: number | null,
	event: Event,
};

export type ErrorKind = "permission" | "capture" | "engine" | "modelsMissing" | "storage" | "job";

export type Event = { type: "stateChanged"; meeting: string; state: SessionState } | { type: "transcriptPartial"; meeting: string; 
/**  0 = mic, 1 = system. */
track: number; text: string } | { type: "transcriptFinal"; meeting: string; line: LineInfo } | { type: "speakerArrived"; meeting: string; speaker: SpeakerInfo } | 
/**  A provisional speaker became "Speaker N". */
{ type: "speakerConfirmed"; meeting: string; speaker: SpeakerInfo } | { type: "speakerRenamed"; meeting: string; speaker: SpeakerInfo } | { type: "speakersMerged"; meeting: string; from: number; into: number } | { type: "speakerSplit"; meeting: string; from: number; speaker: SpeakerInfo } | { type: "speakerNotAPerson"; meeting: string; id: number } | { type: "markAdded"; meeting: string; tMs: number | null } | 
/**  Everything from `from_ms` on was removed (audio, lines, marks, notes). */
{ type: "discardApplied"; meeting: string; fromMs: number | null } | { type: "levelMeter"; meeting: string; micDbfs: number | null; systemDbfs: number | null } | { type: "health"; meeting: string; 
/**  Seconds the live transcript trails the audio. */
asrLagS: number | null; 
/**  Audio skipped by ASR so far (seconds; the final pass fills it). */
asrSkippedS: number | null; aec: boolean } | { type: "jobProgress"; meeting: string | null; job: number | null; kind: string; stage: Stage | null; 
/**  0..1 within the job. */
progress: number | null } | { type: "notesReady"; meeting: string; 
/**  1 = from the live transcript, 2 = after the final pass. */
version: number } | { type: "error"; meeting: string | null; kind: ErrorKind; message: string };

export type Imported = {
	meeting: string,
	duplicate: boolean,
	durationMs: number | null,
};

/**  A final transcript line. */
export type LineInfo = {
	/**  Store segment gid (empty until persisted). */
	gid: string,
	speaker: number | null,
	t0Ms: number | null,
	t1Ms: number | null,
	text: string,
	/**  Two speakers talked over each other. */
	overlap: boolean,
	words: WordInfo[],
};

/**  Recording mode (doc 02 §A). */
export type RecordMode = 
/**  Mic (you) + the call's audio. */
"call" | 
/**  One mic in a room. */
"room";

/**  SessionManager states (brief §7, the Record control). */
export type SessionState = "idle" | "starting" | "recording" | "paused" | "stopping" | "processing" | "ready" | "failed";

export type SpeakerInfo = {
	/**  Session speaker id (stable for the meeting). */
	id: number,
	/**  What the UI shows: a name, "Me", "Speaker N" or "Identifying…". */
	label: string,
	/**  1..=8, or 0 for the shared Others lane. */
	colorSlot: number,
	isMe: boolean,
	provisional: boolean,
	notPerson: boolean,
	others: boolean,
};

/**  Final-pass stages, in order (shown as progress in the UI). */
export type Stage = "decoding" | "refiningSpeakers" | "matchingVoices" | "improvingTranscript" | "writingNotes";

export type Stopped = {
	meeting: string,
	durationMs: number | null,
};

export type WordInfo = {
	text: string,
	t0Ms: number | null,
	t1Ms: number | null,
	lowConfidence: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

